### ISSUE TITLE
servant-docs: Incorrect docs generated for NoContent responses

### ISSUE THREAD

**Issue by adetokunbo** [haskell-servant/servant#1028]
Servant-docs should emit

> ### Response:
>
> - Status code 204
> - Headers: []
> - No response body

but instead emits 

> ### Response:
>
> - Status code 204
> - Headers: []
>
> - Supported content types are:
>
>   - `application/json;charset=utf-8`
>   - `application/json`
>
> - Example (`application/json;charset=utf-8`, `application/json`):
>
>    ```javascript
>
>   ```

because NoContent responses have to set an arbitrary content type. (In this example `'[JSON]`)

Related issues: #498, #683

**Comment by ibarrae** [comment]
I found out this today, would be really helpful if it displays `No response body` as @adetokunbo

**Comment by arianvp** [comment]
How about of having `Verb method cts NoContent` we add a new "Verb" called
`NoContentVerb methods`  which has an `HasSever` instance that skips content negotiation altogether and doesn't force you  to list content types at al.  


Suggested fix:

instead of writing:
```haskell
type API = "blah" :> Verb '204 '[JSON] NoContent
```

We write:

```haskell
type API "blah" :> NoContent
```

and we have an `Has{Client,Server,Docs}` instance for `NoContent` directly.

We could also define

```haskell
data NoContentVerb
```

instead to not break backwards compatibility of existing usage of `NoContent`


We will probably add this to our library https://github.com/wireapp/servant-uverb/issues/4 because we need it for generating correct swagger docs for our client teams at wire.  So we can experiment with this idea bit there and if we like it we can add it to the main `servant` repo.

I'lll be working on this and other `servant` related stuff at MuniHac
