### ISSUE TITLE
Middleware combinator

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#108]
It'd be good to have a general middleware combinator that modifies a sub-api with the specified WAI middleware.

**Comment by freezeboy** [comment]
So basically, we would need something like:

```haskell
data Middleware Wai.Middleware

instance HasServer (Middleware m :> sub) where
  route -- apply the middleware m to "serve sub"

-- and for other contexts, we ignore this portion
instance HasClient Middleware m where
instance HasDocs Middleware m where
instance HasJS Middleware m where
```
Or I am missing something ?

**Comment by jkarni** [comment]
Yup. Converting sub to an duplication directly  (and then applying the middleware) doesn't quite work though, since there is routing information that we need and would lose that way.

**Comment by fizruk** [comment]
@freezeboy if I understand correctly, you want middleware to be a parameter of `Middleware` combinator:

```haskell
data Middleware (m :: Wai.Middleware)
```

That would require promoting functions (`Middleware` is a function) to type-level.
It should be possible with Idris, but unfortunately, not Haskell (even with GHC 8.0).

With recent addition of `Config` in #327, however, `Middleware` combinator might become possible:

```haskell
data Middleware (tag :: Symbol)

instance (HasConfigEntry config (Tagged tag Middleware), HasServer api config)
  => HasServer (Middleware tag :> api) config where
  ...
```

However, I am not sure whether this combinator might be helpful since we usually do middleware-ish things with API combinators (like `AuthProtect`). The `HasServer` basically defines the middleware.

**Comment by jkarni** [comment]
This is not possible in the current design, and I can't see a nice way of making it possible. This is because:

```
type SubAPI = ...
type SuperAPI a = ... :> a
type API1 = SuperAPI SubAPI
type API2 = SuperAPI Raw 
```
Converting `SubAPI` to `Raw` with `serve` and then applying the rest is *not* equivalent to just serving the entire thing directly (because we lose information about how e.g. 404s were generated - whether via the handlers, or the combinators).

I think we should close, since as mentioned I don't think it's possible for the foreseeable future (even if it would be very nice).
