### ISSUE TITLE
Refactor Matrix Params

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#113]
There are currently a couple of problems with matrix params:

  * We do a lot of work handling URLs that's specific to matrix params, even when the combinator that's doing the work is never `MatrixParam` itself. We've verified that the performance penalty of this is significant
  * Matrix params influence the ability of other combinators to use the semicolon character in URLs. 
  * Relatedly, `Raw` endpoints get a modified `pathInfo` that is almost certainly not what we want
 
EDIT: A couple of more issues -
   * Writing combinators is more complex since you have to check whether the path starts with ';'
   * "a;b" and "a/;b" currently end up being treated the same

Both could be addressed by making `MatrixParam` a combinator function rather than a combinator - e.g. `WithMatrix ("name", String) <comb>` where `<comb>` is either a capture or a path literal. 

I'm going to get started on this, but wanted to hear opinions on the concrete syntax. Some options:

   1. `WithMatrix '[("name", Type), ... ] <comb> `
   2. `WithMatrix '["name" := Type, ...] <comb>`
   3. As in `1` or `2`, but the first argument is not a list, s.t. multiple `WithMatrix` must be used.
   4. Both `WithMatrices` and `WithMatrix` (i.e. 1-2 and 3).

I'm also interested in hearing thoughts about the name. I personally like (kosmikus' idea of) using `With` to indicate that this is not a standalone combinator. But of course we could continue using `MatrixParam` and/or `MatrixParams`.

**Comment by jkarni** [comment]
Additionally, changing `MatrixParam` in these ways is also justified from a user's perspective: query params are semantically attached to the entire URL, whereas matrix params are semantically attached to a particular path segment.

**Comment by alpmestan** [comment]
Agreed that this should be changed, even just for the unnecessary work done on *all requests*. @dlarsson may have some comments on this proposal, being the original author of the matrix params combinators. I personally like either 1/ or 2/ but I haven't used matrix params in a work project yet, so... =)

**Comment by dlarsson** [comment]
This sounds like a good idea. Indeed, matrix params are a attached to a path segment, so there's several benefits with this change. It makes the semantical connection much more explicit, the implementation much more local, and not everyone has to pay the price.

I don't have a strong opinion about the various solutions. The "With" prefix sounds like a good idea though. Since they're somewhat similar to query parameters, I guess one could argue that the syntax to define them should be similar too, e.g. option 3.

**Comment by jkarni** [comment]
Agreed. The disadvantage I see with 3, though, is that it becomes less self-evident which argument describes the path, and which the flag, in the `WithMatrixFlag` case:
```
WithMatrixFlag "thisIsParam" "thisIsPath"
```
1-2 would instead have:
```
WithMatrixFlag '["thisIsParam"] "thisIsPath"
```

OTOH, we *may* be able to have special behaviour for boolean arguments (i.e., just check for presence, *or* a boolean assignment) in which case we might not need `MatrixFlag` at all. As @dlarsson points out, we would probably then want similar changes for `QueryFlag` for consistency.

**Comment by kosmikus** [comment]
Well, for modularity, we want `Query*` parameters to be allowed everywhere in the API, I guess. So even though it's strange, I think we should allow `SomePath :> QueryParam ... :> SomeMoreStuff :> QueryParam :> ...`.

For `MatrixParams`, this is essentially a non-issue. Because they're attached to a specific position, they have to be listed at that point.

One option is to have another infix operator (but I'm not sure about a good name, so I'm currently just proposing `With`), and then say

   "foo" :> "bar" `With` MatrixParam ... `With` MatrixParam :> "baz" :> Get ...

So `With` would be left-associative and have higher-priority than `:>`, so that in the above code, all parameters are grouped with `"bar"`.

The other option I think is ok is

    data WithMatrix (item :: *) (matrixargs :: [*])

where `item` is the API path item (using the terminology of the paper) we wish to modify, and `matrixargs` is a list of arguments (with their syntax still up in the air). But it's true that having all matrix parameters in a list makes them look very stylistically different from query parameters, and perhaps makes it less obvious that they'd still be added to the handler function one by one (and that's the plan, right?).

**Comment by jkarni** [comment]
@dlarsson Will you have time to work on this in the near future? I won't, but it's a pretty serious issue. If you think you can tackle it, great, but otherwise we might consider removing matrix params until we've figured out how to solve the problems above (which would be a shame).

**Comment by dlarsson** [comment]
Hi Julian. Sorry for having been absent for a long while. I'll try allocate
some time for this. I'll keep you posted on progress, so you know if you
need to retract it or not. I'll be away until next week though, so won't
have time to look at it on very short term.

2015-09-16 16:13 GMT+02:00 Julian Arni <notifications@github.com>:

**Comment by jkarni** [comment]
Closing until someone has a nice PR

**Comment by soenkehahn** [comment]
cc: @dlarsson @jkarni @kosmikus @alpmestan 

I'm working on bringing back matrix parameters here: https://github.com/plow-technologies/servant-matrix-param
