### ISSUE TITLE
support pagination

### ISSUE THREAD

**Issue by ibotty** [haskell-servant/servant#125]
Whenever I find time I will start to write it myself. That bug report is to explore the design space.
- It should work with `Link` headers (`rel` in `next`, `prev`, `last`, `first`) (see [RFC5988](https://tools.ietf.org/html/rfc5988)).
- It should be possible to specify how many items to return (e.g.: "?per_page=100").
- I have used two different schemes to generate these `Link` urls in the past. There might be more worth supporting.
  - use a "?start_id=xxx" (This is usually way more efficient),
  - use a "?page=x"

**Comment by alpmestan** [comment]
Just putting down some thoughts I've had on the topic, in the past.

``` haskell
data Paginated a = Paginated
  { page :: Int
  , totalPages :: Int
  , entries :: [a]
  } deriving (Eq, Show, Generic)

instance ToJSON a => ToJSON (Paginated a)

type Paginate c cts a = QueryParam "page" Int :> c cts (Paginated a)

-- Example
type API = "users" :> Paginate Get '[JSON] User
```

And then some machinery to help write request handlers that return paginated results.

**Comment by christian-marie** [comment]
It'd be nice/crucial to design this so that the provider of these paginated results can load only the page it needs.

The whole point of pagination in many cases is that the data set is larger than memory,  or at least unwieldy, right? We should probably answer that question.

**Comment by alpmestan** [comment]
Yes, but it's hard to be more helpful/specific without tying ourselves to a particular data store or something, isn't it? With some `Link` magic we could probably add a field with the URL to the next page, but what do you think this should look like? Feel free to drop a few ideas or lines of code.

**Comment by jkarni** [comment]
The auth ideas in #70 show a way of being data-store agnostic that to my mind should be our general tack. (I.e., just a type "tag" that is associated with a `Range -> IO a` function that can be used as a parameter to `Paginate`).

I do wonder about using `Paginate Get ...` rather than `Paginate ... :> Get ...`. (Redirects, in #117 are relevant.) What's the general story about when you'd expect an overlapping instance in the last argument, when a type synonym over the method (as per @alpmestan suggestion), and when a `:>` combinator?

**Comment by alpmestan** [comment]
@christian-marie by the way, just to clarify, the `entries` list isn't supposed to contain all the values, just the ones for the current page. But it's just a sketch anyway.

@jkarni `Paginate` above is a type synonym because it acts on the 2nd param of `Get` **and** adds a query string parameter.

As to the general story... My thinking:

- overlapping in the last argument: just for (), hopefully, otherwise it's a mess and often goes with having a lot of duplicate code.
- type synonym that takes the method as a param: like `Paginate` above or my suggested `Redirect`, for method-"agnostic" combinators and/or when you have to insert new combinators + tweak the method's 2nd parameter or something.
- A good old `:>`-friendly combinator otherwise, if the "action" of the combinator is local to where it's encountered and does interfere with anything else (`Capture`, `ReqBody`, ...).

This is just off the top of my head so I gave this very little thought.

**Comment by GildedHonour** [comment]
Please give me an update, if I want to implement pagination, should I implement it manually?

**Comment by soenkehahn** [comment]
Nothing about pagination is in the `servant` or `servant-server` package. So yes, you have to roll your own.

**Comment by jkarni** [comment]
Closing. Please re-open if you think that was a mistake.

**Comment by ibotty** [comment]
I can't reopen, but I think _the interface_ does not depend so much on the database.

(I guess most of what follows has been said above, including by me.)

AFAICT, there are two common ways: using a running count (which will be used e.g. with `OFFSET` in SQL), and using the last seen (or next) id (to be used with e.g. `WHERE id_col > last_id`), which is usually way more efficient. Both can (and should) be within a link rel=next/prev header, so IMO it does make sense to support it in core servant. Many parts of the implementation won't be database specific.

When I was implementing paging in other web frameworks, I could usually reuse most parts when I moved to another database/data source.

**Comment by jkarni** [comment]
@ibotty I reopened.

OK, so let's try to clarify what could be done here.

There are the aspects that are not related to the database. This includes:

1. Getting the relevant page and number of results from the query parameter
2. Doing nice things with `Link` headers in the response

(1) we can currently do with existing query parameters - I don't immediately see what else there is to it besides `QueryParam "page" Int :> QueryParam "per-page" Int`. To currently do (2) we'd just add a response header. What's not clear to me is what we could do, in a DB-agnostic way, to make this better.

That said, there is a lot of non-DB agnostic stuff that seems interesting to explore - maybe in this issue. But I don't think anything in this repo should be non-DB agnostic.

**Comment by alpmestan** [comment]
Well, for starters, packaging up (1) and (2) into some reusable "component" that people could drop into their API types could be handy. @ibotty I'm all ears if you have further suggestions, other ideas and what not.

**Comment by KtorZ** [comment]
Hey guys, we just open-sourced and released this: 

https://hackage.haskell.org/package/servant-pagination-1.0.0/

Feedbacks and ideas are welcome :)

**Comment by arianvp** [comment]
Sweet!  Perhaps we can add it to the website?

**Comment by alpmestan** [comment]
Both haskell-servant.github.io and the readthedocs pages live on github and take pull requests :)

For the former, there's a dedicated repo with that name in the haskell-servant org. For the latter, sources live under `doc` in this very repository.

**Comment by KtorZ** [comment]
Thanks for info! I'll definitely push that forward.

**Comment by jkarni** [comment]
Closing (but happy to take PRs linking docs to https://hackage.haskell.org/package/servant-pagination)

**Comment by erlandsona** [comment]
This is awesome... does anyone here know how to write this function?
https://stackoverflow.com/questions/25732876/entityfield-in-persistent
Such that I could write a `HasPagination` instance for a persistent `Entity record` where the field coming in from a request would map to the name of the field on the record.

I realize this dips into the dependent types territory but it seems more reasonable that someone from this community might have some expertise in this domain that would know what extensions / syntax functions would enable me to write this mapping without having to resort to maintaining a long pattern match mapping strings to their concrete `EntityField rec typ` representations ala `UserName` or `UserEmail` etc...

**Comment by alpmestan** [comment]
(I don't know `persistent` much, so I can't help, but is there a servant component to the question?)

**Comment by erlandsona** [comment]
Apologies, and sure. Can you provide any other example instances of `HasPagination`? I'm trying to "monkey see monkey do" with it but extend it thusly. From the docs:
```
instance HasPagination Color "name" where
  type RangeType Color "name" = String
  getFieldValue _ = name -- also what's the purpose of the `Proxy "name"` argument to getFieldValue here.
```
I've written a bunch of not working instances that look sort of like this:
```
instance HasPagination Account "email" where
  type RangeType Account "email" = Text
  getFieldValue _ = accountEmail -- accountEmail is just the record accessor on a data Account = Accout {}
```
Which works for defining the instance but not at the call site. I need that instance to kick out a Persistent `Filter Account` which in persistent looks like `AccountEmail :: EntityField Account Text` where a `Filter Account` is `AccountEmail ==. "username_string"` where `(==.) :: EntityField rec typ -> typ -> Filter rec`
So I've tried writing:
```
instance HasPagination (Entity Account) "email" where
  type RangeType (Entity Account) "email" = Text -> Filter Account
  getFieldValue _ = (AccountEmail `like`)

like :: EntityField record Text -> Text -> Filter record
like field val = Filter field (Left $ Text.concat ["%", val, "%"]) (BackendSpecificFilter "like")
```
and
```
instance HasPagination (EntityFilter Account Text) "email" where
  type RangeType (EntityFilter Account Text) "email" = Text -> Filter Account
  getFieldValue _ = (AccountEmail `like`)
```
Ideally I'd like to generalize this instance to dispatch to any `EntityField rec typ` and have it do the right thing across all my DB types where it can otherwise throw 500 or something.

**Comment by erlandsona** [comment]
Here's the term level for reference.
```
api :: ConnectionPool -> Api AsServer
api pool = Api
    { accounts = genericServer crud
    , todos =  genericServer $ crud -- This is the broken piece cause I don't know what I'm doing.
        { list_ = do
            mranges <- extractRange
            pure $ returnRange (fromMaybe range) (db $ selectList (maybeToList range) [])
        }
    }
    where
        crud ::
            (PersistEntity record
            , PersistEntityBackend record ~ SqlBackend
            ) => (Crud record) AsServer
        crud = Crud
            { list_ = db $ selectList [] []
            , show_ = (maybe (throwError err404) pure =<<) . db . getEntity

            , create_ = (NoContent <$) . db . insert_
            , update_ = (NoContent <$) ... db ... repsert
            , delete_ = (NoContent <$) . db . delete
            }

        db :: MonadIO m => ReaderT SqlBackend IO record -> m record
        db = liftIO . (`runSqlPool` pool)
```
