### ISSUE TITLE
Inconsistent Header

### ISSUE THREAD

**Issue by tvh** [haskell-servant/servant#126]
The way headers are handled is inconsistent right now. When talking about request headers, they are always treated as optional. `ResponseHeaders` forces them to be there.

Maybe it is worth going for a braking change here. I see 2 options:

```.haskell
data IsRequired = Required | Optional
data Header (sym :: Symbol) (required :: IsRequired) a
```
or
```.haskell
data RequiredHeader (sym :: Symbol) a
data OptionalHeader (sym :: Symbol) a
```

**Comment by mf59816** [comment]
I second this.

I like option 2 slightly better.  It is more concise, at least as long as there won't be any further `IsRequired` constructors.

**Comment by jkarni** [comment]
Good point. More genereally, I really don't like the `ResponseHeaders` system. It forces us into overlapping instances, and the number of such instances grows exponentially.

One thing I've been thinking about is using algebraic effects or mtl-like approaches.

    (HasError m 400, HasHeader m ("ETag", ETag)) => m User

Or some such (this needs some fleshing out). Then maybe we could move response headers to the left of `:>`.

All of this is only marginally related to the issue in question, but it's something to keep in mind.

(Otherwise, I'm also in favour of the second option.

**Comment by alpmestan** [comment]
Technically, the second option could be implemented using the first one though, to avoid code duplication.

``` haskell
data IsRequired = Required | Optional
data Header (sym :: Symbol) (required :: IsRequired) a

type RequiredHeader (sym :: Symbol) a = Header sym 'Required
type OptionalHeader (sym :: Symbol) a = Header sym 'Optional
```

**Comment by oswynb** [comment]
Would it make sense to have optional/required for query parameters as well?

**Comment by alpmestan** [comment]
If it would for you (i.e you have a use case for that / you could benefit from that), that's a defendable suggestion. Again, my query params are always optional because we can access the endpoint *without* them so I try to only push optional arguments in the query string, so I don't feel super-strongly about this.

However, this would change a bit the way we represent/use some combinators, so let's make a decision on this and stick to it in the future to avoid breaking people's code as often as we've been doing these past few months.

@jkarni opinion?

**Comment by fizruk** [comment]
Looks like this issue is intersecting/superseded by #241.

@jkarni should we maybe close both in favour of a new issue discussing more general solutions (e.g. `Required` combinator)?

**Comment by jkarni** [comment]
Or rename #241 ? Either way, let's close this.
