### ISSUE TITLE
How do i to tell servant to bind 127.0.0.1 address instead of binding 0.0.0.0 (any) ?

### ISSUE THREAD

**Issue by rodjjo** [haskell-servant/servant#1298]
I want to build an app that does not expose the port to other networks.

**Comment by erewok** [comment]
Servant helps you produce a `Wai.Application` but doesn't run it for you. For that, you will usually use something like Warp, which has a `run` function as well as a `runSettings` function. `runSettings` takes some settings and a `Wai.Application` and runs a server. Among those settings, you can set the the [`HostPreference`](https://hackage.haskell.org/package/warp-3.3.11/docs/Network-Wai-Handler-Warp.html#t:HostPreference), which would allow you to bind to localhost instead of all interfaces. It looks something like this (untested):

```
main
let settings = setHost "127.0.0.1" defaultSettings
runSettings settings YourServantApp
```

This isn't specific to Servant, but people often use Warp to run Servant app, so it may apply to your app. See [Warp](https://hackage.haskell.org/package/warp-3.3.11/docs/Network-Wai-Handler-Warp.html) for more info.

**Comment by rodjjo** [comment]
thanks
