### ISSUE TITLE
FromText/ToText is too generic of a typeclass name

### ISSUE THREAD

**Issue by gregwebs** [haskell-servant/servant#136]
There can be many different ways to represent something textually. `ServantText` or `ApiText` would be better names for the typeclass.

I authored a module with a ToText typeclass. In hindsight it would have been better to come up with a different typeclass name. http://hackage.haskell.org/package/shakespeare-2.0.5/docs/Text-Shakespeare-Text.html#v:toText

**Comment by jkarni** [comment]
Sure, just as there are many ways of representing a type as JSON or HTML or String etc, or `Ord`ering them, etc. I don't entirely see what's special about `Text`. In my mind, we're not writing a class that's that specific to `servant` - it's just that there aren't any such well-established typeclasses in the Haskell ecosystem that I know of, in the way that there is for, say, `String`.

(Though I admit the specific encoding limitations in URLs are a consideration, taking those too seriously ourselves, rather than just documenting them clearly enough for users, might start the balkanization of all our typeclasses, which is to my mind a sign of failing to recognize that in a lot of cases, the de/serialization coincides across purposes, and for the other cases, there are always newtypes.)
