### ISSUE TITLE
default To/FromText to use `PathPiece`

### ISSUE THREAD

**Issue by gregwebs** [haskell-servant/servant#137]
Servant is doing about the same thing all other web frameworks are doing so it could make a lot of sense not to reinvent things too much.

Leveraging the `path-pieces` dependency means

* code re-use
* avoiding orphan instances

Code re-use would help [new users avoid confusion](http://www.reddit.com/r/haskell/comments/3agvoa/converting_strings_to_persistent_keys_in_servant/).
Note that keeping the typeclasses in servant forces orphan instances. This can be avoided by moving the To/FromText typeclasses into a separate typeclass, which would be the same as using `path-pieces`.

**Comment by jkarni** [comment]
Thanks for opening the issue. I have a few qualms with the proposal:

   - `PathPiece` isn't at all the right name to represent what the class does. Sure, it's used in captures, but it's also used in a number of other places. Our sense was that, rather than having (quite a few) separate classes for every use of that particular de/serialization (from/to `Text`) which must be implemented separately and often repeatedly, it is easier to newtype-wrap in case the instance doesn't match the use. This is the approach throughout the library, and doing otherwise would special-case `Text`.
  - I don't see how this avoids orphan instances any better than the current approach. 
  - (In fact) We have many more instances that we like than does `path-pieces`. If we were to port them over, then we'd have many more orphan instances (in the `servant` packages) than we do now.
  - I don't like having serialization and deserialization in the same class. It (a) leads to less precise error messages when something isn't implemented; and (b) requires implementing functionality you might not need.

It also seems to me like if we were to go down the route of reusing existing typeclasses, `text-show` would be a more intuitive package to consider, though that wouldn't solve the problem of `fromText`.

**Comment by gregwebs** [comment]
I have been meaning to get back to this, but just been a bit busy lately. I appreciate that you took the time to respond, but I don't think any of the points listed are relevant, and the suggestion to use `text-show` and the `Show` typeclass is non-sensical given that the typeclass is used for url captures.

I think we are talking past each other because I haven't written any code yet. This is all I am suggesting:

``` haskell
class ToText a where
  toText :: a -> Text
  default ToPathPiece a => a -> Text
  toText = toPathPiece
```

**Comment by jkarni** [comment]
Thanks, that makes things clearer - it wasn't clear to me that you were suggesting defaulting to `path-piece` rather than using it directly. (I also agree that `text-show` was a poorly thought-out suggestion.)

I still don't see how my points were irrelevant, though. E.g., you said we'd be avoiding orphan instances, and I still don't see how. I also don't see how, given that we use `FromText` for things other than paths, why `FromPathPiece` gets special treatment (by being the default implementation). I also don't see any practical advantage for users anymore. 

The confusion you mentioned and linked to seems to have nothing at all to do with the name `FromText` (just with the implementation, which wouldn't be any different). And even if it did have to do with the name, this wouldn't as far as I can tell be making it that much better.

**Comment by gregwebs** [comment]
> you said we'd be avoiding orphan instances, and I still don't see how

path-pieces is a tiny separate package that a database library like persistent can depend upon and define an instance for. persistent would never depend on servant

> I also don't see how, given that we use FromText for things other than paths, why fromPathPiece gets special treatment (by being the default implementation).

A typeclass method can only do 1 thing. If you use if for multiple things, its behvior must be additive of the constraints for each thing it is doing. In this case I think that a url path piece is the most constrained case, and that any constraint applying to another case would apply there also.

Without a recognition of what the behavior is you may end up arguing that FromText has undefined semantics and therefore cannot use anything which has semantics, which is not a good place to be. Servant really should re-think its approach here to one which has semantics. It has been stated that a multiple typeclass approach is too inconvenient. In that case I would try to default as much as possible.

``` haskell
class ToApiData where
  toUrlPiece :: a -> Tex
  default toUrlPiece :: ToPathPiece a => a -> Text
  toUrlPiece = toPathPiece
  toHeader :: a -> ByteString
  toHeader = encodeUtf8 . toUrlPiece
  toQueryParam :: a -> Text
  toQueryParam = toUrlPiece
```
