### ISSUE TITLE
Add `HasStatus ()`?

### ISSUE THREAD

**Issue by ocharles** [haskell-servant/servant#1440]
Currently you can't return `()` with `UVerb`, because `()` doesn't have a `HasStatus` instance (leading to a very weird type error, but that's another story...).

What do you think about having

```haskell
instance HasStatus () where
  type StatusOf () = 200
```

?

**Comment by alpmestan** [comment]
Right, `UVerb` is still a bit rough around the edges. However, wouldn't you want a different status if you were returning `()` from a GET vs e.g POST or PUT endpoint?

**Comment by ocharles** [comment]
Would you? What else would you return? I guess you're thinking something like a `210 Created`?

**Comment by alpmestan** [comment]
(I suppose you meant `201`, but) Indeed. I was just trying to say that there's an argument to be made that the meaning of `()` as a response, and how this is mapped to a status code, could depend on the context (e.g HTTP verb).

In fact, having just commented on https://github.com/haskell-servant/servant/issues/1433 - I wonder if as a user (and quite likely contributor to a project where you're not the only developer), you wouldn't prefer being explicit about this and using something like @pcapriotti's `EmptyResponse`?

I don't have a strong opinion here, because like I said on that ticket, neither the pre-UVerb or the UVerb infra seem to hit the sweet spot I've been looking for, for many years. It always seems like we're dancing around what we would really like to write.

**Comment by ocharles** [comment]
Thanks, I did mean `201`.

I understand what you're saying. To me, I don't think I have much stake in the game - I don't care about status codes to that level. 

I'm not sure about `EmptyResponse` - I'm interacting with a Servant server from Elm, and having all responses be valid JSON is simpler than sometimes having an empty response body and sometimes having JSON (unless I misunderstood `EmptyResponse`)

**Comment by alpmestan** [comment]
Ah, I see, that is indeed a different scenario. I'm not too enthusiastic about just picking `200` for `()` but if you have any suggestion that would solve your issue while not making a definitive choice like the one discussed above, I would be fine with that.

**Comment by ocharles** [comment]
I don't think I have any suggestions. I can do `WithStatus 200 ()`, it's just annoying to have to wrap things up in `WithStatus`. I guess maybe `servant-server` could be clever and do that wrapping for me, but that's probably excessively smart. Shall we close this for now? It sounds like I might best just defining `OK`, and giving that `ToJSON`, `FromJSON` and `HasStatus` instances.

**Comment by alpmestan** [comment]
> It sounds like I might best just defining `OK`, and giving that `ToJSON`, `FromJSON` and `HasStatus` instances.

I would personally find it clearer, as someone reading the code, no ambiguity whatsoever.

We can close indeed, if you think this is a good enough solution to your initial enquiry. :-)

**Comment by ocharles** [comment]
Sure 🙂 I just don't want to add another unresolvable issue! If it comes up again, we can always revive the discussion. Thanks for your thoughts!
