### ISSUE TITLE
automatic handling of OPTIONS requests

### ISSUE THREAD

**Issue by psygnisfive** [haskell-servant/servant#154]
if you're building an API using servant, you'll need to do cross origin requests. if the origin happens to be in Chrome, Chrome will send out a pre-flight OPTIONS request to ensure that it can perform the actual request. servant really ought to handle OPTIONS request automatically, generating relevant bits of information. im not sure if this is possible for everything, however. headers might be a problem?

**Comment by alpmestan** [comment]
I think we can "automagically" add `OPTIONS` handlers where appropriate without too much trouble. I'm just not sure what is expected to be found in the response. Does anyone have a good link/reference on that?

**Comment by psygnisfive** [comment]
RFC2616 has some explanation

https://tools.ietf.org/html/rfc2616#section-9.2

**Comment by jkarni** [comment]
I'm in favour of supporting `OPTIONS` in the way @alpmestan suggested, quite independently of CORS. But surely there's a different approach to CORS? Middleware exists for it (e.g. [wai-cors](https://hackage.haskell.org/package/wai-cors-0.2.3/docs/Network-Wai-Middleware-Cors.html)), and middleware can't possibly reflect enough to do a proper `OPTIONS`. Does it just overshoot the `OPTIONS`?

**Comment by jkarni** [comment]
@kosmikus might have some suggestions here, but re: being able to reflect supported methods on any endpoints, my first thought is to add an extra field to the router with the information we need. On the other hand, this starts to feel like we have the wrong abstraction, since we would be repeating certain bits of information (e.g. method).

**Comment by psygnisfive** [comment]
OPTIONS != CORS, importantly. Chrome and Firefox simply use OPTIONS as part of implementing their check that cross-origin requests are valid, but OPTIONS exists for things other than that.

**Comment by alpmestan** [comment]
What do the other haskell (or any language really) web frameworks/servers do?

**Comment by arianvp** [comment]
To summarize the discussion we had about this IRC last night:

Browsers do a Preflight-request for CORS (They do an `OPTIONS` to check which commands they can send to the HTTP server).  And it's part of the [W3C recommendation](http://www.w3.org/TR/cors/) to handle this gracefully.

Basically `wai-cors` allows us to tell what to return with `OPTIONS` by setting  `corsMethods` on the `CorsResourcePolicy`   e.g.
```
-- simpleMethods = ["GET", "HEAD", "POST"]
customPolicy = simpleCorsResourcePolicy { corsMethods = simpleMethods <> ["DELETE", "PUT"] }
```
The problem with this is that you globally define what methods are available for CORS for all your resources with `wai-cors`, whilst more fine-grained control would be cool.

Because we have all the routing information at hand in servant, it would be possible to define a CORS policy per resource instead of globally.

**Comment by obscaenvs** [comment]
How do I handle OPTIONS requests in the meantime? I am a bit sad since I coded my api thinking that handling OPTIONS would be a minor detail, but I realise now that it's not so minor after all... I really have to implement CORS since JSONP wouldn't cut it.

**Comment by codedmart** [comment]
@obscaenvs Have you taken a look at https://hackage.haskell.org/package/wai-cors?

**Comment by obscaenvs** [comment]
Yep. I based my work on that package, and everything worked nicely until I realised that the endpoint for servant couldn't handle OPTIONS... And on that note, a glitch in my mental model just revealed itself. I think I've got it, thank you. Should I perhaps delete this? :)

**Comment by fizruk** [comment]
Is this still relevant? `wai-cors` seems to be solving the issue.

**Comment by jkarni** [comment]
I'm in favour of keeping it open - `wai-cors` solves CORS, but automatic handling of `OPTIONS` in my opinion would still be nice for documentation purposes.

**Comment by christian-marie** [comment]
> The problem with this is that you globally define what methods are available for CORS for all your resources with wai-cors, whilst more fine-grained control would be cool.

This is certainly a good use case; is it worth pursuing if browsers don't unanimously support per-resource access control and instead decide to flip out? Maybe they would gracefully degrade to a reasonable error message and it's worth pursuing.

**Comment by fizruk** [comment]
@jkarni ok, how this issue interacts with #278?

**Comment by jkarni** [comment]
They're duplicates, in my opinion. Closing in favour of #278 .
