### ISSUE TITLE
Sending a large JSON document stuttering and slow

### ISSUE THREAD

**Issue by HugoPeters1024** [haskell-servant/servant#1611]
I am making a frontend browser application that interacts with a servant backend server on the same machine (localhost). One of the larger cases involves sending a 240MB JSON document and takes around 18 seconds. When inspecting with my browser's network manager I can see that the request remains 'pending` for the first 4 seconds of so and then when the download begins it downloads in batches. First 30MB or so very fast, than a pause of 1 second etc.

It is not a bandwidth issue as I have tried adding a gzip middleware which compresses the request to only 16MB but the download has exactly the same timings and characteristics (except that it is batches of 1MB or so)

Does anybody have any suggestions on how I might improve the situation?

**Comment by arianvp** [comment]
Might be that Aeson just doesn't like such large objects and you're running into GC pauses.

I'm assuming your json document is a list; You could try to use Line-Delimited JSON (https://en.wikipedia.org/wiki/JSON_streaming)  instead of one large JSON object

```
{"doc1"}
{"doc2"}
```

Instead of

```
[
{"doc1"}, {"doc2"}
]
```


And then utilise Servant's streaming capabilities to stream the json documents as they come.

```
type Api = StreamGet NewLineFraming JSON (SourceIO Document)
```

There's a tutorial here: https://docs.servant.dev/en/stable/cookbook/basic-streaming/Streaming.html

**Comment by HugoPeters1024** [comment]
Thanks for the suggestion! Unfortunately the document represents a large AST so it'll be quite non trivial to cut it up.

**Comment by HugoPeters1024** [comment]
I have since abandoned the project where this issue popped up (for other reasons than this issue). So since I no longer have a project to reproduce this issue I think it would be better to close this for now.
