### ISSUE TITLE
Test suite fails property validation

### ISSUE THREAD

**Issue by mdorman** [haskell-servant/servant#170]
When building servant-client under nixos, we are seeing failures because the QuickCheck properties fail to validate.  Specifically:

  works for a combination of Capture, QueryParam, QueryFlag and ReqBody FAILED [1]

You can find a recent sample buildlog at http://hydra.cryp.to/build/1001134/nixlog/1/raw

**Comment by jkarni** [comment]
Thanks. We've seen this before in #165 when bumping the warp version bound, and it seems hydra is using warp 3.1.0. We're still not sure what's causing it, but will look into it.

**Comment by jkarni** [comment]
Going from `warp == 3.0.13.1` to `3.1.0` is all it takes to trigger this issue. It's starting to look like it might be `warp`.

**Comment by jkarni** [comment]
Since we do actually have an upper bound that should prevent the error (but is ignored by nix), and since we have a different ticket ( #164 ) which is tracking discussions about a version bump and the associated issues, I'm closing this. Thanks for the report, and let me know if you think it should be reopened.

**Comment by codedmart** [comment]
@mdorman until this issue is solved upstream you can solve this by overriding your haskellPackges for warp to 3.0.
