### ISSUE TITLE
servant-foreign: too strict bounds on hspec

### ISSUE THREAD

**Issue by sternenseemann** [haskell-servant/servant#1704]
Requests `hspec >=2.6.0 && <2.10`, but also works with hspec 2.10.* according to my testing.

**Comment by ysangkok** [comment]
The bounds mentioned in OP were already fixed in

* https://github.com/haskell-servant/servant/pull/1690

I don't have permission on Hackage, so I haven't made a release or revision for it.

But you can see on Hackage that bounds were updated to `<2.12`: https://hackage.haskell.org/package/servant-foreign-0.16/revisions/ by maksbotan.

So I am closing this, since hspec-2.11.7 is currently the newest version: https://hackage.haskell.org/package/hspec
