### ISSUE TITLE
Idea to improve routing

### ISSUE THREAD

**Issue by Drup** [haskell-servant/servant#184]
@alpmestan ask me to put that here, so here it is. :)

At the moment, in order to do the routing you build a decision tree of the set of routes. You then execute this decision tree pretty much directly, potentially using backtracking.
I think it would be very beneficial to optimize it, based on the fact that the order of the decision is unimportant. To give an example, the order between "checking the method is GET" or "checking that the path starts in /foo" doesn't matter.
(Note: the order between *branches* is important since choice favor left, but not the order between decisions).

With this property, it should be possible to minimize two criterion: 
- short depth 
- minimal backtracking. 

That should provide a more efficient routing. I do not deny the fact that it could be premature optimization. :)

**Comment by Drup** [comment]
Example:
```haskell
type Bla = "very" :> QueryFlag "long" :> Capture "route" String :> Get '[Whatever] Bla
      :<|> Capture "thing" String :> Put '[Whatever] Bli
```

If you first check the method, you will never backtrack and you have only once choice to make.

**Comment by alpmestan** [comment]
We could even consider running *some* checks concurrently, I guess.

**Comment by jkarni** [comment]
@Drup If we check method first in your example, and then the path, wouldn't be end up returning a 404? But then if the path were "very/something" what we'd really like to return is 405. And to do that we still need backtracking. Did I miss something?

More generally, I'm inclined to think the order of checks should be the order of the priority of HTTP error codes (which is what we have). I think there are trade-offs in terms of performance (neither options seem to be strictly more performant in all cases, intuitively).

**Comment by jkarni** [comment]
@Drup can you expand a little? Or should we close this? 

We also know e.g. that a hashmap over all routes would be more efficient than our current (master) trie implementation, but our benchmarks suggest we're already ahead of the curve in terms of speed, and we have several use-cases in mind (e.g. HATEOAS) which we would not be able to implement (easily) if we went that route. So so far we've been trying to stick to an implementation that roughly matches the intended semantics of routing (e.g., path *pieces* get matched one-by-one), especially since servant is very extensible and that generally helps making writing new combinators easier.
