### ISSUE TITLE
Making a DSL for constraints-descriptions 

### ISSUE THREAD

**Issue by dredozubov** [haskell-servant/servant#230]
Creating a way of describing things more granularly than Aeson-instances will make it possible to generate a very strict spec in such formats as json-schema. I believe it'll make integration with other projects/companies/vendors more seamless and less painful. I'm willing to work on it, if we'll have a clear course on this matter.

**Comment by alpmestan** [comment]
@jkarni did some work on this [here](https://github.com/haskell-servant/cretheus) and has talked to many folks about ideas he's got on this topic. To be honest this isn't something I have been investigating much, so I'll just let Julian provide a summary of what's been said about this.

However, now that I think about it, I may have the beginning of an idea.

In my [servant-ede](http://hackage.haskell.org/package/servant-ede) package, I have an `HTML` content type. But it's not actually a content type per se, but more like a "parametrized content type", that takes a (type-level) filename pointing to a template file. This means you can use it like this:

``` haskell
type API = "users" :> Capture "userid" UserID :> Get '[HTML "user_profile.tpl"] User
```

What if, instead of having just `JSON`, we had:

``` haskell
type API = "users" :> Capture "userid" UserID :> Get '[JSON UserJSONSchema] User
```

where `UserJSONSchema` is either a type that describes a JSON structure (just like servant's API types describe web APIs), or it's just a type somehow associated with a value-level description of the schema (using one of the existing libraries), in the same way that the current `JSON` gets associated to `aeson`'s encoding/decoding functions?

**Comment by jkarni** [comment]
@alpmestan we don't need to change anything in the API types - we can just use the same mechanism we currently have to check `User` is an instance of `JsonSchema` or whatever. 

=== 

I think 90% of the work consists of things quite outside `servant`, but I think I'd be useful to a lot of people besides us. 

`Aeson` doesn't let you reify the structure of the JSON, so you can't built a json schema from a `From/ToJSON` instance. Other libraries, such as `JsonGrammar`, keep more info. Probably we'd like a bidirectional class like `JsonGrammar`'s.

`hjsonschema` does a lot of what we need re: JSON schema itself. As I see it, what we need in something that mixes `JsonGrammar` and `hjsonschema`. Ideally, the end user describes the structure of their JSON in a way similar to `JsonGrammar` in a class (say `HasJsonSchema`), but with optionally some validation taken from a validation DSL, and we have functions 

```
encode :: HasJsonSchema a => a -> ByteString
decode :: HasJsonSchema a => ByteString -> Maybe a
toSchema :: HasJsonSchema a => a -> JsonSchema
```
where of course we can choose to delegate `encode` and `decode` to `aeson`.

(Note that the package `json-schema` doesn't have anything to do with JSON Schema.)

We could then do quite a lot. We could do serious HATEOAS. We could properly get started on API Blueprint integration. And we could of course make `servant-docs` better.

As a side note, the `cretheus` approach was to try to make this library a drop-in replacement for `aeson` - modulo monadic instance declarations (i.e., up to applicative). I now think that's sort of misguided. It'll never be fully drop-in, and we might as well have bidirectional parsing.

Let me know if any of this is unclear.

**Comment by dredozubov** [comment]
@jkarni mentioned one of the key points i had in mind, but forgot to mention for some reason - we can have request validation with helpful error messages for `JSON` requests. Making it optional is a good thing too, it won't be too restrictive on the user.

Not so sure about HATEOAS, but json-schema and api blueprint is a nice touch. Afaik `hjsonschema` is an implementation of the recent draft.

**Comment by jkarni** [comment]
I'm having to convert some digestive-functors stuff from another framework and now have another reason to want this.

Here's a thought: http://lpaste.net/142998

It's still incomplete. We would likely need generics. Types would have to be polymorphic in all fields that might want validation. But this also makes it a lot easier to declare JSON and HTML instances once and for all. 

Interestingly, with phantom types we could use the same DSL to write safe versions of e.g. head etc.

**Comment by jkarni** [comment]
A slightly different take, integrating it with a very general smart constructor: http://lpaste.net/143001

**Comment by jkarni** [comment]
Closing this - development for it is taking place in https://github.com/jkarni/verdict
