### ISSUE TITLE
Validation of request body

### ISSUE THREAD

**Issue by alexbiehl** [haskell-servant/servant#24]
At the time of writing the payload of the `ReqBody a` type needs to have an instance of FromJSON. As I want to perform possibly complex validation (with database accesses etc.) so no invalid data can be constructed. My validation function has the form `MonadIO m => Value -> m (Either Object a)`. Is it possible to build such a combinator?

**Comment by jkarni** [comment]
No. You could of course have an intermediate data-type `UnvalidatedData` and then perform further validation after the handler receives the unvalidated data. If that's not good enough, you could, I'm pretty sure, construct your own `ReqBody`-like combinators to do the job of performing extra validation (conversion from `UnvalidatedData`) so that your handlers only ever see validated data.

**Comment by jkarni** [comment]
You'll need to separate out IO validation

```
class Validatable a where
   type Unvalidated :: *
   validate :: Unvalidated a -> IO (Either Err a)

```
Then *something* like:

```

instance (Validatable a, FromJSON (Unvalidated a), HasServer sublayout) => HasServer (ReqBody a :> sublayout) where
    type Server (ReqBody a :> sublayout) = a -> Server sublayout

    route Proxy subserver request respond = do
        mrqbody' <- eitherDecode' <$> lazyRequestBody request
        validated <- validate <$> mrqBody'
        case validated of
            Left e -> respond . failWith $ InvalidBody e
            Right v -> route (Proxy :: Proxy sublayout) (subserver v) request respond

```
Should work. (I haven't actually tried compiling this, though.)

Let us know if it doesn't!

**Comment by alexbiehl** [comment]
Thank you, this is awesome. Together with the less restrictive Monad constraint in servant-server master this seems like a really great thing!

**Comment by alpmestan** [comment]
Does it properly solve your issue (in which casewe can close it) or do you feel like we should have something for thid in servant itself?

I'm not too fond of the latter because JSON now becomes only one content type among many others and the needs are quite specific, but since we are close to releasing new major versions of everything, we try to wrap up any outstanding PR/issue :)

**Comment by alexbiehl** [comment]
Thank you for your help! It's solved partially, I can't thread config values through the typeclass instances but when servant lands support for custom monads in handlers this shouldn't be a problem at all anymore.

**Comment by alpmestan** [comment]
Uh? Could you give some more details on what you'd like to do that's not possible? (although it seems to be a separate issue from the one you raised here, above)

**Comment by alexbiehl** [comment]
I have some Formlets defined using the digestive-functor package. I
validate it using digestive-functors-aeson. The validation process uses
some configuration value I pass the application on startup. Through the
typeclass instance I cannot pass any additional information e.g. my
configuration. And that's where I need my application Monad which is able
to read that config value. That's why I think it would be useful to be able
to use custom monad transformers in handlers.


Alp Mestanogullari <notifications@github.com> schrieb am Do., 12. März 2015
um 15:28 Uhr:

**Comment by jkarni** [comment]
Exactly this issue came up on the servant IRC channel yesterday or day before. The only workaround I can think of is to use something like an IORef:

```
myConfig :: IORef (Maybe Cfg)
{-# NOINLINE myConfig #-}
myConfig = unsafePerformIO $ newIORef Nothing

instance HasServer ...
     route = ... readIORef myConfig >>= ...

main = writeIORef myConfig ... >> serve ...
```

ImplicitParams and `reflection` might work, but I haven't tried. Though to be honest, aside from the fact that it's not obvious in type signature that you have to write the IORef before startup, I don't actually mind the solution above.

**Comment by alexbiehl** [comment]
Yes, I thought about that too. It's a good trick to get some work done. 

However, I saw https://github.com/haskell-servant/servant-server/commit/f7af3b14d25ed9a10b49624872c843b07522c228 and thought custom monads in handlers were on it's way?

**Comment by jkarni** [comment]
yeah, you'll be able to use custom monads in your *handlers*, but it's not obvious (and I suspect not true) that you'll be able to use arbitrary monads in the *combinator instances*. Maybe we should start thinking about that too, but I doubt we'll have a good solution for the next release.

**Comment by alexbiehl** [comment]
Ah, thank you for making that clear to me. I think this ticket can be
closed then.


Julian Arni <notifications@github.com> schrieb am Do., 12. März 2015 um
16:44 Uhr:

**Comment by jkarni** [comment]
No problem! And if you come up with a different solution than the IORef, we'd love to hear it!
