### ISSUE TITLE
BaseUrl with more than server name yields invalid URLs

### ISSUE THREAD

**Issue by edsko** [haskell-servant/servant#240]
For instance

``` haskell
client api (BaseUrl Http "example.com/api" 80)
```

yields a client trying to connect to

```
example.com/0.6:80
```

instead of

```
example.com:80/api
```

**Comment by alpmestan** [comment]
Right, this is "expected". The solution to this *right now* is to put the `"api"` prefix in your API type. However, I remember talking about this with someone already, and suggested that we could add a field in `BaseUrl` to let folks specify a prefix, so that your code would become:

``` haskell
client api (BaseUrl Http "example.com" 80 $ Just "/api")
```

or something like that. The code you just showed would not work because the second field of `BaseUrl` is supposed to be *just* the host/IP.

Would that work for you?

**Comment by edsko** [comment]
Sure, either is fine. (And your work-around is what I'm currently using.)

**Comment by jkarni** [comment]
Already done in #203 / #204 .

**Comment by edsko** [comment]
Ah, apologies. Closing as duplicate.

**Comment by alpmestan** [comment]
I somehow completely forgot we already merged a PR for this =)
