### ISSUE TITLE
MimeReader uses lazy ByteStrings whereas warp headers are strict ByteStrings

### ISSUE THREAD

**Issue by hherman1** [haskell-servant/servant#323]
If there's no benefit for MimeReaders being lazy then I suggest we use the strict ones so it agrees with the larger architecture. Would save a reasonable number of imports/implementation for users who want to instantiate MimeReader.

**Comment by jkarni** [comment]
I think I'm missing something. `MimeRender` is used to generate the response body, not headers. And we use `responseLBS` for that, which takes lazy `ByteString`s

**Comment by hherman1** [comment]
this was about warp headera. i wanted to reuse my code for generating a strict bytestring response header with minimal work

**Comment by jkarni** [comment]
To answer your question, then, there is a benefit to having them be lazy - lazy ByteStrings is what we ultimately need for the response.

Are you using content-types for rendering headers too?

**Comment by hherman1** [comment]
No im not because i needed to add it to a HasServer instance

**Comment by fizruk** [comment]
@hherman1 my understanding is that you shouldn't use `MimeRender` to render header.
With `servant-0.4` you should use something like `encodeUtf8 . toText` and with HEAD you should use [`toHeader`](http://hackage.haskell.org/package/http-api-data-0.2.2/docs/Web-HttpApiData.html#t:ToHttpApiData).

Can you probably share some code with us, so that we better understand your problem?

**Comment by jkarni** [comment]
Closing - please reopen if you feel this was a mistake.
