### ISSUE TITLE
Make it easier to test that we have instances for core combinators for all interpretations

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#333]
I imagine we could have an API that contains all core combinators at least once. In the different interpretations we would just add a test case where we use an instance for that big API. To ensure that all interpretations are there.

I want this for #327.

Should I put this into `Servant.API.Internal.Test` (or something like that) and expose it in the package? If we don't want to add an exposed module, I wouldn't be sure how to do it.

(cc: @jkarni)

**Comment by jkarni** [comment]
Great idea. Maybe CPP the module so that by default it is not there, if that doesn't get too complicated?

**Comment by fizruk** [comment]
Alternatively, maybe we can collect all sorts APIs for testing in a separate package, like `servant-samples`/`servant-api-samples`/`servant-test-samples`?

Or maybe `servant-hspec`/`hspec-servant` with not only common API samples, but also common `hspec` machinery (I suspect there is some, didn't check).

**Comment by soenkehahn** [comment]
@jkarni: I don't want to tinker with `CPP` unless I absolutely have to.

@fizruk: A separate package seems a bit too heavy-weight just for one module with one type alias.

I think if we mark this as an `Internal` module there is no real harm in just exposing this in `servant`.

**Comment by fizruk** [comment]
@soenkehahn the idea is that this separate package would declare all the useful sample APIs for testing, not just the mega API. E.g. we can extract APIs from [`ServerSpec.hs`](https://github.com/haskell-servant/servant/blob/master/servant-server/test/Servant/ServerSpec.hs) and [`ClientSpec.hs`](https://github.com/haskell-servant/servant/blob/master/servant-client/test/Servant/ClientSpec.hs).

I think having test APIs unified is a good thing, because then we know that for this set of APIs all of the packages actually work. Also for any new `servant-*` package will then use this set of APIs rather than invent its own, likely incomplete set.

I also think that some `hspec` machinery specific to `servant` might get factored out too.

**Comment by soenkehahn** [comment]
@fizruk: Thanks for clarifying. I think that's a reasonable idea. I **do** think that having the API types next to the test cases is nice and that wouldn't be the case if they all get factored out into a separate package. I'm not very passionate about that, though.

More importantly: I think putting this in a separate package is out of scope of this PR. At least I don't want to work on refactoring the test-suite right now. @fizruk: Do you think it's problematic to include this module in `servant` now (clearly marked as `Internal`) and then remove it later if/when someone finds the time to create something like `servant-api-samples`?

**Comment by fizruk** [comment]
@soenkehahn refactoring test suites is clearly out of the scope of this PR!

I merely brought up an idea which now seems to be reasonable and we probably should move its discussion into a separate issue. Sorry for the confusion!

**Comment by soenkehahn** [comment]
@fizruk: No problem! :)

**Comment by jkarni** [comment]
Done in #334
