### ISSUE TITLE
Generating a client for an API with nested routes is impossible(?)

### ISSUE THREAD

**Issue by statusfailed** [haskell-servant/servant#335]
I've been advised that generating a client for this API is impossible:

    type Response a = EitherT ServantError IO a

    type API =
           "bar" :> Get '[JSON] Value
      :<|> "foo" :> Capture "foo" Int :> (    "a" :> Get '[JSON] Value
                                         :<|> "b" :> Get '[JSON] Value
                                         )

    api :: Proxy API
    api = Proxy

    getBar :: Response Value
    getFooA :: Text -> Response Value
    getFooB :: Text -> Response Value

It's not clear from the tutorial or the docs how to write the client-generating line, e.g.:

    -- What do I write here?
    getBar :<|> (getFooA :<|> getFooB) = client api (BaseUrl Http "example.com" 80)

@aaronlevin advises me on freenode #servant that this may currently be impossible.

**Comment by statusfailed** [comment]
As a workaround, you can "flatten" the API, changing the relevant bit to this:

     type API =
           "bar" :> Get '[JSON] Value
      :<|> "foo" :> Capture "foo" Int :> "a" :> Get '[JSON] Value
      :<|> "foo" :> Capture "foo" Int :> "b" :> Get '[JSON] Value

Then the pattern match works as expected. This is a bit boilerplatey though!

**Comment by aaronlevin** [comment]
Thanks, @statusfailed, for submitting.

The surprising bit about this is that `servant-server` will behave appropriately, in that you will supply some type like:

```haskell
server :: Server API
server = \i -> (xxx :<|> yyy)
```

(iirc some details may be absent but I was testing this out with auth).

I'm not sure how the client solution should look. if we could pattern match on the route, we'd be ok, but it's unclear how to do this.

**Comment by fizruk** [comment]
@statusfailed it is definitely not impossible to have client for this API. Maybe not without some extra pattern matching on user's site, but it's possible and I use this sort of APIs for work.

The approach I use is to create a `data` structure for each level of nested API (including the whole API):

```haskell
{-# LANGUAGE RecordWildCards #-}

type Response = EitherT ServantError IO

type Bar = Value
type Foo = Value
type FooId = Int

type API
    = "bar" :> Get '[JSON] Bar
 :<|> "foo" :> Capture "foo_id" FooId :>
         ( "a" :> Get '[JSON] Foo
      :<|> "b" :> Get '[JSON] Foo )

data ApiClient = ApiClient
  { getBar :: Response Bar
  , mkFooClient :: FooId -> FooClient
  }

data FooClient = FooClient
  { getFooA :: Response Foo
  , getFooB :: Response Foo
  }

mkApiClient :: BaseUrl -> ApiClient
mkApiClient baseurl = ApiClient{..}
  where
    apiClient = client (Proxy :: Proxy API) baseurl 
    getBar :<|> fooClient = client baseurl

    mkFooClient fooId = FooClient{..}
      where
        getFooA :<|> getFooB = fooClient fooId
```

`ApiClient` is more flexible than just top-level client functions, because you now can provide `BaseUrl`.
I also like the idea that you only need to provide common parameters once, not per request.

Although this might seem like a lot of code, it's not. `data` declarations are just a bit more verbose than top-level client function signatures and `mkApiClient` consists mostly of pattern matching (which you would need for top-level declarations as well). `RecordWildCards` extension makes it easier to automatically construct `ApiClient` and `FooClient` given variables with their field names are in scope.

To use such a client you would need to construct `ApiClient` and then `FooClient`:

```
>>> :set -XRecordWildCards
>>> let ApiClient{..} = mkApiClient (BaseUrl Http "example.com" 80)
>>> :t getBar
getBar :: Response Bar
>>> let FooClient{..} = mkFooClient 123
>>> getFooA
getFooA :: Response Foo
```

As @aaronlevin mentioned, your server code will need to pass the common parameter to every subserver:

```haskell
server :: Server API
server = serveBar :<|> serveFoo

serveBar :: EitherT ServantErr IO Bar

serveFoo fooId = serveFooA fooId :<|> serveFooB fooId

serveFooA :: FooId -> EitherT ServantErr IO Foo
serveFooB :: FooId -> EitherT ServantErr IO Foo
```

**Comment by jkarni** [comment]
You can also [Canonicalize](https://github.com/haskell-servant/servant/pull/23) on the API prior to generating clients for it. Maybe it's time to bring `Canonicalize` back...

**Comment by statusfailed** [comment]
Ah I see! Thanks @fizruk , this is exactly what I was looking for :-)

**Comment by fizruk** [comment]
@jkarni I am not sure `Canonicalize` is the right solution here (and AFAICT earlier discussion indicates that `Canonicalize` might not be a good solution for anything).

I think it is natural to want something like `Canonicalize` because current client examples only show how to get a bunch of top-level client functions. But I think nested clients correspond more naturally to nested APIs. Just like nested APIs facilitate code reuse, nested clients remove code duplication when using them (you only need to specify common parameters once). This can be useful when working with a particular resource (operations on which have common parameters, e.g. resource ID).

@jkarni if you agree, perhaps we should to add some examples/tutorials with client `data` types.

@statusfailed can this issue be closed?

**Comment by alpmestan** [comment]
I wholeheartedly agree that a few "complex" examples of client derivation can't hurt! Feel free to even cook up a patch for the tutorial if you feel like explaining the examples as well.

**Comment by statusfailed** [comment]
@fizruk I am happy for this to be closed, but agree that extra docs could really help here.

**Comment by soenkehahn** [comment]
I'll close this then.
