### ISSUE TITLE
API Blueprint

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#35]
_From @AndrewRademacher on March 25, 2015 14:44_

Has there been any consideration for writing servant docs output in API Blueprint format 1A?

_Copied from original issue: haskell-servant/servant-docs#17_

**Comment by jkarni** [comment]
There's been some talk of outputting compatible formats (to API Blueprint, Swagger, etc.) but as far as I know no one has really started work on it...

**Comment by jkarni** [comment]
_From @alpmestan on March 26, 2015 10:58_

Consideration, yes, definitely! Anything that can help integrate servant with existing tooling is appreciated. We however haven't started working on that. Would you be interested in working on that? We would definitely be around to help, if needed.

**Comment by jkarni** [comment]
_From @AndrewRademacher on March 29, 2015 20:17_

I would be interested in doing it, but I have some bandwidth issues to resolve first.

**Comment by s9gf4ult** [comment]
There is also [RAML](http://raml.org/)

**Comment by Porges** [comment]
If this goes *to* Swagger it would also be really nice to have a codegen backend *from* Swagger.

**Comment by nrolland** [comment]
swagger would be very nice...

**Comment by alpmestan** [comment]
We forgot to mention it here, @dmjio is working on this.

**Comment by dmjio** [comment]
Rewriting swagger for version 2.0 is in progress. Going from swagger to servant is also in progress, reading from swagger Json / yaml is possible (swagger codegen), probably will use a QQ for this.

**Comment by dmjio** [comment]
http://github.com/dmjio/servant-swagger <--- for the interested

@Porges, yes that would be nice. Only issue I see is that we'd need to use something like template haskell (put the swagger.json in a quasi quoter) or generics. In that case the API type, along with the data constructors produced wouldn't be directly modifiable, since they were generated. A user would need to specify a lot of metadata about each individual type before generation. It wouldn't be impossible, it would just be incredibly difficult :) Also, how would we handle things like custom combinators?

Suppose we have something like this
```haskell
$(generateFromSwagger apiMetaData [swagger|
  { 
     .. swagger json goes here....
  }
])
```
which puts `api = Proxy :: Proxy GeneratedAPI` and a lot of types in scope. These types are now no longer directly editable, but only by adjusting json... Do you think people would want that?

**Comment by jkarni** [comment]
Now that `servant-swagger` is here, I don't think we have any intention of doing this (though if someone else is interested, we'd of course be happy to see it implemented). Closing.
