### ISSUE TITLE
Post endpoints always have status code 201, not always appropriate

### ISSUE THREAD

**Issue by dino-** [haskell-servant/servant#371]
I'm working on a REST server with Servant that uses a POST instead of a GET because the query data is large. The result of this request is always existing data, never created. I don't believe a 201 status code is appropriate for what I'm doing but I can't understand how to change this to 200 for the POST.

I can see in the code in Servant.Server.Internal that the Post endpoint is fixed to always use status201. I think this should maybe be changed. In the meantime, is there a workaround I can use? I'm having problems figuring out how to "adjust" the status code for non-failing responses.

I am using servant-server-0.4.4.6 acquired via cabal from Hackage.

**Comment by fizruk** [comment]
@dino- this has been fixed in #276.

You can either wait for the 0.5 release (which should be this month I think).
Or you can use the `master` branch of this repo.

If you don't want to update `servant`, you can define your own `MyPost` combinator.
You'd have to copy all the instances you use (e.g. `HasServer`, `HasClient`, `HasSwagger`, etc.).
Then you can change the status code in those instances to whatever you want.

Feel free to reopen if #276 does not solve your problem.

**Comment by 3noch** [comment]
As an aside, is it not possible to put large query data in the body of a `GET`?

**Comment by dino-** [comment]
@fizruk: Fair enough. I think I'll wait for a later release.

@3noch: I could put a body with a GET, yeah. I put it to the client-side team and they would rather continue to use the POST with 201 code for now as the most-correct option.

Thank you
