### ISSUE TITLE
Make `enter` magic available from `servant-client`

### ISSUE THREAD

**Issue by gromakovsky** [haskell-servant/servant#395]
I was looking for a way to derive client functions which run in another monad than `EitherT ServantError IO` without writing tons of boileplate. I haven't found anything in `servant-client` and in related part of tutorial. However, then I tried using `enter` magic and it worked. It's not obvious that `enter` is suitable for client too, at least for newcomer. So I think it should be somehow available from `servant-client` library or at least mentioned in documentation (maybe I'm just too blind and didn't find it?).

**Comment by soenkehahn** [comment]
No, you're not too blind. :) My guess is that the fact that `enter` works for `servant-client` is more accidental than anything else. (Just FYI.)

**Comment by alpmestan** [comment]
Well, client functions and server-side handlers have the same "shape" as far as `enter` is concerned, but I never really thought about using it for client things. I guess we could add a note about that somewhere in the tutorial? :)

**Comment by gromakovsky** [comment]
I think it is good idea to note about that in the tutorial. I find it useful to be able to convert client monad. For instance, one may want to catch some errors (e. g. redirects) and do something with them. Also one may want to run it in some custom `MonadIO`.

Also I don't like that I need to add `servant-server` as dependency of `servant-client` (at least I have a feeling that I'm doing something wrong). One option is to move it into `servant`, but of course I don't know whether it's good idea (I can live with `servant-server` dependency by client).

**Comment by soenkehahn** [comment]
Some notes:

1) I think `servant-client` should be reworked a fair bit. The core should be pure and just produce (functions that produce) request stubs. (Containing path, queryparams, headers and request body.) And not do any IO or the like. These should be returned in a structure tied together with `:<|>`s. (This core should maybe not live in `servant-client` anymore, because it can also be used for other things, like safe-links.)
2) I think we generally want to have some convenience functions to work with API types and `:<|>` concatenated values. They should live in `servant`. (And `enter` could be one of them, so yes, it should move to `servant`, IMO.)

**Comment by jkarni** [comment]
Done in #478
