### ISSUE TITLE
 Sending Generic Content-Type in Servant & Generating API Docs

### ISSUE THREAD

**Issue by ecognium** [haskell-servant/servant#400]
I was trying to relay some binary data back to the client and I was trying to figure out how send generic `content-type` headers.  This question and the suggested answer is here: http://stackoverflow.com/questions/35636829/sending-generic-content-type-in-servant

I followed @user2141650's approach and it works for what I am trying to do. However, it breaks `servant-docs` and I get `Could not deduce (Servant.API.ContentTypes.IsNonEmpty '[]) arising from a use of ‘Doc.docs’ ` 

I tried the `addHeader` approach but it does not let me overwrite `content-type`. It will be nice if there is a clean way to set headers (overwriting default ones if necessary). 

In the meantime, appreciate any suggestions on what I can try to satisfy the docs type error. 

Thanks!

**Comment by ecognium** [comment]
I found a way to solve the `docs` issue. I just ended up creating a custom type like `IMAGE` in my original question. Since `AllCTRender` seems to be overriding the Accept instance, it works out ok. Still feels a bit hacky overall.

**Comment by fizruk** [comment]
@ecognium you should probably try also [`servant-swagger`](https://haskell-servant.github.io/posts/2016-02-06-servant-swagger.html) for documentation.
Maybe together with [`servant-swagger-ui`](https://github.com/phadej/servant-swagger-ui).

It should be both easier to use and much more helpful as a documentation than `servant-docs` (at least as the latter is right now).

**Comment by ecognium** [comment]
@fizruk  thanks for the tip about the Swagger doc. I did try it but I am stuck at how to provide a ToSchema instance for LBS.ByteString (One of my API responses is a blob which come back as ByteString). 

Also, `servant-docs` was using my `ToJSON` instances so I did not have to recreate any of them for generating the docs. With Swagger, I need to create `ToSchema` in addition to `ToJSON` (although 90% of it  is derived via `Generic`). Are there additional examples of how to do `ToSchema`  instances? For example, I have:

`data MyRec =  Rec | Unknown String`

Which I pattern match in my `ToJSON` 

    toJSON (Unknown code) = object ["input" .= "UknownValue", "original" .= Just code]
    toJSON r              = object ["input" .= show r, "original" .= Nothing] 
 
 
How would I do such derivations for ToSchema?

**Comment by fizruk** [comment]
@ecognium for `ByteString` there are two options, both of which can be [found in `Data.Swagger.Schema`](http://hackage.haskell.org/package/swagger2-2.0.1/docs/Data-Swagger-Schema.html#g:3):
- `binarySchema` — for arbitrary sequence of octets;
- `byteSchema` — for base64 encoded data.

You probably should not use `ByteString` as is, but rather wrap it in a newtype (so that it can be clear what this sequence of bytes is representing). E.g.:

```haskell
newtype VideoStream = VideoStream LBS.ByteString deriving (Generic)

instance ToSchema VideoStream where
  declareNamedSchema _ = return $ NamedSchema (Just "VideoStream") binarySchema
```

For the `MyRec` example, I would recommend a different JSON representation, if possible.
Generic deriving mechanism of `swagger2` for sum types derives a schema for [`ObjectWithSingleField`](https://hackage.haskell.org/package/aeson-0.11.1.0/docs/Data-Aeson-Types.html#t:SumEncoding) JSON encoding. That will covert `Rec { ... }` constructor to `{"Rec": ...}` and `Unknown "code"` to `{"Unknown": "code"}`. This representation reflects Haskell's sum types better.

If you cannot change the representation, you can always go with the manual `ToSchema` instance:

```haskell
instance ToSchema MyRec where
  declareNamedSchema _ = do
    sString <- declareSchemaRef (Proxy :: Proxy String)
    return $ NamedSchema (Just "MyRec") $ mempty
      & type_ .~ SwaggerObject
      & description ?~ "Either an Unknown with the original string or a Rec."
      & properties . at "input" ?~ sString
      & properties . at "original" ?~ sString
      & required .~ [ "input" ]
```

I hope the code is self-explanatory!
This schema doesn't verify that `"original"` property must be present (and not `null`) when `"input"` is `"Unknown"`. That's why I have suggested a different JSON encoding.

There are more examples and explanations in the Haddock documentation for [`swagger2`](http://hackage.haskell.org/package/swagger2-2.0.1/docs/Data-Swagger.html) and [`servant-swagger`](http://hackage.haskell.org/package/servant-swagger-1.0.3/docs/Servant-Swagger.html). There's also an [example project using `servant-swagger`](https://github.com/haskell-servant/servant-swagger/tree/master/example), you might want to check out!

Swagger, albeit not ideal, is a great medium that opens some great tools for servant users.
Documentation is just one part of it! There's also client/server code generation, automated testing and more. Please see the [`servant-swagger` and `swagger2` announcement post](https://haskell-servant.github.io/posts/2016-02-06-servant-swagger.html)!

BTW, you can also ask Swagger-related questions on IRC `#servant` channel.

**Comment by ecognium** [comment]
Awesome. Thank you so much @fizruk. Apologize for hijacking the thread to talk about Swagger. 

`binarySchema` was what I was missing. The ByteString was inside another data type but since I was trying to derive using Generic, the compiler was asking me to provide an instance for ByteString.  

I need to check if I can change the JSON response (the client assumes this format). I will study your manual definition of MyRec a bit more -- I can pattern match and change it to my needs but also would like to understand how it works.

**Comment by soenkehahn** [comment]
This issue is a bit noisy with all the `swagger` and `docs` related comments. @ecognium: Are you still interested in this? Do you want to open up a new issue explaining the remaining problems?

**Comment by ecognium** [comment]
@soenkehahn I am satisfied with my workaround for now.  I don't know if things have changed with the latest version of servant though. 

The main issue before I hijacked it to talk about swagger :) is that it there is no dynamic way to send content-types. If nobody else feels this is a worthwhile enhancement, it is perfectly fine to close the issue.  This may be a very rare use case.

**Comment by soenkehahn** [comment]
Alright, thanks for the feedback. I'll close. Please, open another issue, if you feel this is important.
