### ISSUE TITLE
Less specific 404 takes precendence over more specific 405 when serveDirectory is used

### ISSUE THREAD

**Issue by sol** [haskell-servant/servant#408]
Given the following API

```haskell
type MyAPI = "run" :> Post '[JSON] () :<|> Raw

server :: Server MyAPI
server = liftIO runJob :<|> serveDirectory "static"
```
doing a GET request to `/run` will result in a 404 instead of the desired 405.

I assume this is because we try handlers in order until we get something different from 4xx.  I'm also not sure what's the right way to fix this, so I'm mainly leaving this here to get more input.

**Comment by sol** [comment]
One way to fix this could be to have some ordering (from less specific to more specific) over 4xx errors, and then always return the most specific error.  404 would the be at the beginning of the list.

**Comment by fizruk** [comment]
@sol I don't think it is a good idea to run multiple endpoints that match the same path.
Note that it is possible that 4xx error is thrown halfway through the application logic.

In my opinion a better approach would be to isolate `Raw` in a subpath, e.g. `"static" :> Raw`.

In any case, in `master` there already exists [an ordering of 4xx error](https://github.com/haskell-servant/servant/blob/master/servant-server/src/Servant/Server/Internal/Router.hs#L92).
But it only happens when routing is being done, that is when servant combinators to the left of `:>` are being processed. But since `Raw` handles routing in the application code, servant can't put it into routing.

It might be possible, however, to create a new `StaticDir` combinator, which would separate routing part of `serveDirectory` and allow for better error fallbacks.

**Comment by jkarni** [comment]
Yeah, `Raw` is the problem. We could perhaps make an exception type that `Raw` could throw to indicate routing status, but even then most `Application`s wouldn't work out of the box.

**Comment by jkarni** [comment]
While the situation isn't great, I don't think there's anything we can really do about it. Can I close this?

**Comment by kosmikus** [comment]
@jkarni There should be an open issue that we need to move away from `Raw` for serving static files if possible. Is there already?

**Comment by 3noch** [comment]
This is related: https://github.com/haskell-servant/servant/pull/350

**Comment by jkarni** [comment]
Closing in favour of #507
