### ISSUE TITLE
How can I go with parsing json objects for POST (new) and PUT (update) which have some fields empty?

### ISSUE THREAD

**Issue by jjmornim** [haskell-servant/servant#447]
I have a data and post method handler :
    
```
    data MyData = MyData
      { myId :: Int
      , currentDate :: UTCTime
      , isActivated :: Bool
      , realName :: Maybe String
      , login :: String
      -- .......
      }
    --..........
    "items" :> ReqBody '[JSON] MyData :> Post '[JSON] Int64 
```
And a function itself:
```
    myAdd ::MyData -> ExceptT ServantErr IO Int64
    myAdd myData = 
      --......
```
And

```
instance ToJSON MyData where
  toJSON (MyData myId currentData isActivated realName login) =
    object [ "id" .= myId
      , "current_date" .= currentDate
      , "is_activated" .= isActivated
      , "real_name" .= realName
      , "login" .= login
    ]

instance FromJSON MyData where
  parseJSON (Object v) =
    MyData 
      <$> v .: "id"
      <*> v .: "current_date"
      <*> v .: "is_activated"
      <*> v .:? "real_name"
      <*> v .: "login"

```

Note that in `MyData` some fields are Maybe. 

However, the fields, for example, `myId` and `currentData` don't have to be provided from a client on POST (new) and PUT (update) because Postgresql itself should take care of them by generating the default values.

But this post request for inserting a new item to the database returns an error:

```
    curl -v \
         -H "Content-Type: application/json" \
         -d '{"isActivated": false, "realName": "abc", "login": "login123"}' \
         localhost:3344/
```
which is
```
that `key "myId" not present.`
```

How can make it understand that `myId` and `currentData` are generated by Postgresql? 

Should I create one more constructor MyDataNew without  `myId` and `currentData`? Or should I make them Maybe in the main one?

**Comment by 3noch** [comment]
> `<$> v .: "id"`

You need to make the `id` field optional the same way that `real_name` is optional. The type must be `Maybe` and you need to use `.:?`.

**Comment by soenkehahn** [comment]
Or you can provide a default value using `.:?` and `.!=`. (See http://haddock.stackage.org/lts-5.11/aeson-0.9.0.1/Data-Aeson.html#v:.-33--61-)

**Comment by jjmornim** [comment]
Thanks. So, assuming I need to insert and update MyData, each of fields should be Maybe? Even though in the database they're mandatory.

**Comment by soenkehahn** [comment]
Well, in the *interface* to the database they're not mandatory, since postgres fills in the default values. At least when talking about inserting into the db.

So this is definitely a viable option: wrap every field in a `Maybe`.

Another option is to have two (or more) types for different uses that still represent the same thing. (Maybe that's what you hinted at in your original question.) I've seen people write one type for parsing `JSON` and then immediately convert to another type that's used internally in the program and that's easier to work with.

So you could consider having one type with `Maybe`s (for inserting into the db and `PUT` requests) and one without (for reading from the db, `POST` requests and working internally, since this type is probably more practical to work with).

**Comment by 3noch** [comment]
I might be missing something, but I think you only need to put `Maybe` around fields that can be NULL in the DB or have defaults when inserting/updating.

**Comment by jjmornim** [comment]
I see. I think I need 2 or 3 constructors for the different things. Because in here:
```
      newId <- execute cn "insert into my_data (currentDate, isActivated, realName, login) values (?, ?, ?, ?)" myData
```

I shouldn't pass the "id" whether even if it's Maybe or has a default value, correct? And it gets passed automatically from "myData".  What would you recommend?
My real "MyData" has more fields.

**Comment by soenkehahn** [comment]
One more note: I wouldn't use multiple *constructors* in the same *type*, but rather different *types*. Otherwise you end up with partial selectors.

That doesn't really help with your actual questions, sorry. I guess this really depends on lots of things in your particular project. And is also a bit a matter of taste.

**Comment by jjmornim** [comment]
Thanks.
