### ISSUE TITLE
Debug/trace logging toggle.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell-servant/servant#449]
I have a need to understand where specifically a request fails.  Often when I have a javascript front-end and a servant back-end, there might be some small JSON encoding issue, or maybe the Content-Type header is set wrong, or similar.

Dumping the request and response is a good start, but it would be nice to get a trace of what happens, especially at points where things can go wrong, and to be able to see what is going wrong in a log.

Another thing that would be good to support in such a mechanism are ekg counters.  In a production setup, individual requests might not be too interesting to look at, but ekg counters that count the same things (number of successful JSON decodes vs failed ones broken down by endpoint for example) would be good to graph.

A third thing that could be plugged in there are performance counters, just doing a `gettimeofday` at that point in time and log/graph it.

A fourth thing that one might want to do, but that would require a different machinery is a chaos monkey, where some requests are asked to fail so check the robustness of the larger system as a whole.

**Comment by kosmikus** [comment]
Dumping the request/response is something that can relatively easily be done on the WAI middleware layer.

A trace of what happens is a very interesting request, and quite doable. But the question is how exactly to do it. Simply adding the machinery for potentially tracing into the main routing machinery might slow it down. We could have a separate `runRoute` function doing the tracing. In any case, how do we parameterize `serve` on whether to do tracing or not?

Also, how do we write the trace? Simply print to `stdout` or `stderr` or use some logging framework?

EKG counters and performance counters sound like things to me again that could be done on WAI level, or is there anything in particular where you need access to info only the Servant layer has?

Four is certainly something for doing on the Servant-level, but it's not exactly clear to me what is desired here? Do you want the server to just fail on random requests, in order to test robustness of a client? Or do you want to test robustness of the server itself somehow?

**Comment by alexanderkjeldaas** [comment]
I had a dump of the request, but in this case I was still scratching my head.  Of course it was a stupid mistake on my side, but confirmation that my handler was actually run, routed to etc. would have shortened the debug cycle (saved me 30 minutes probably).

I think a logging framework should be used.  I don't know what kind of optimizations are in the logging frameworks, but writing to a file descriptor should ideally happen in a separate thread for latency reasons.

For EKG, if I put them at the WAI level, can I get information about which route was matched so the counters can be broken down by handler?

For Chaos Monkey, the idea is to test for robustness in a larger system http://techblog.netflix.com/2011/07/netflix-simian-army.html

**Comment by rvion** [comment]
@alexanderkjeldaas : as kosmikus said, just use some wai middleware:

Servant Server is based on wai, so you can just  change 

```haskell
run port $ serve api apiServer
```

to
```haskell
import Network.Wai.Middleware.RequestLogger

run port $ logStdoutDev $ serve api apiServer
```

because `serve api apiServer :: Application`

**Comment by jkarni** [comment]
I think for the first point @rvion 's suggestion seems like the way to go. For the second and third, there's [servant-ekg](https://github.com/anchor/servant-ekg), though I don't think it's maintained anymore (though the people at Anchor have in the past been okay to pass down maintainership). 

@alexanderkjeldaas @kosmikus why should the fourth be done at the servant, rather than WAI middleware, level?

**Comment by rvion** [comment]
> @alexanderkjeldaas @kosmikus why should the fourth be done at the servant, rather than WAI middleware, level?

according to http://techblog.netflix.com/2011/07/netflix-simian-army.html:

>  Chaos Monkey, a tool that randomly disables our production instances to make sure we can survive this common type of failure without any customer impact

@alexanderkjeldaas : I even think it should be done at some proxy level.

> that would require a different machinery

I don't think so. You can always use your own monad that randomly fails.

**Comment by kosmikus** [comment]
@jkarni I wasn't really sure what it is that's desired. So no strong opinion from my side.

**Comment by jkarni** [comment]
OK, my take is that there's nothing to be done at the servant level, so closing this. Please re-open if you think this was a mistake.

**Comment by alexanderkjeldaas** [comment]
I'm back.  Another API, same issue.

A request fails with "Bad Request", but where in the Servant type does it go wrong?

For example I have:

```
type VerificationBaseAPI =  V1_ResultList
                            :<|> V1_ResultItem

type V1_ResultList = "v1" :> "result"
                     :> Get '[JSON] [Text]

type V1_ResultItem = "v1" :> "result"
                     :> Capture "filename" FilePath
                     :> Get '[JSON] R.SendPhotoResponse
```

Now when I request `http://localhost:10312/v1/result/foo/bar.baz` where is the problem..?  Why am I getting "Bad Request"?

1. Is it the missing header (the type above is wrapped in some session magic)?
2. Does the two "v1/result" types somehow overlap?  What is really the semantics?
3. Oooooh.. I should have used `CaptureAll`, not `Capture`!

Now if only there was a trace option.. then that would be obvious.

This cannot be discovered at the wai level.

**Comment by adnelson** [comment]
Yeah, often the really tricky thing is figuring out why a servant handler didn't match a route, when you expected it would. Is it because it couldn't parse a `Capture` as the given type? Is it because you misspelled a URL? Is it because you forgot a querystring parameter? Etc. It would be really nice to have a debug with servant where it says "trying to match <ROUTE> against <HANDLER> ... failed due to <XYZ>" etc

**Comment by alexanderkjeldaas** [comment]
@jkarni could this issue be re-opened?
