### ISSUE TITLE
Re-export `Application` from `Servant` and `Servant.Server`

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#462]
Since it's the result type of `serve`, I think this would make sense.

**Comment by freezeboy** [comment]
I think it can make sense from `Servant.Server`, but Servant is the common part, so when generating a Client I would prefer not to depend on such things.

**Comment by soenkehahn** [comment]
I was referring to the module `Servant`, not the package. Confusingly the module `Servant` is in the package `servant-server`.

(Why is that, btw? @alpmestan @jkarni)

**Comment by kosmikus** [comment]
I support this. Although, by the same logic we'd also have to re-export `Text` now, as it's the result type of `layout` ... Do we want that as well?

I'd also be in support of deprecating the `Servant` module in favour of using `Servant.Server` explicitly.

**Comment by soenkehahn** [comment]
I don't have an opinion on `Text`, since I expect `layout` will be much less often used.

> I'd also be in support of deprecating the Servant module in favour of using Servant.Server explicitly.

Would you then at some point add `Servant` to the `servant` package, exporting the same things `Servant.API` exports? Then it would coincide with the package names completely.

**Comment by alpmestan** [comment]
The `Servant` module exists (and is in `servant-server`) "because" of me. I wanted to have a _single_ module that people could import in order to get started writing an `Application`, and only if they wanted fancier things they would have to import additional things. The main use of _servant_ has been, is, and probably will always be to write web services/apps, so it made sense to me to put a `Servant` module forward that would export the most common things one needs when writing a servant app. I still think this is a good idea but if a majority of contributors/users disagree, we can do something else.

**Comment by soenkehahn** [comment]
@alpmestan: I basically agree with everything you're saying, but your arguments equally well apply if that one module would be `Servant.Server`. `Servant` is slightly shorter to type, but I think that saving to type 7 characters is not worth the confusion that this creates. `servant` can very well be used without writing a server, but this fact can be a bit unintuitive, since it differs from what most other web frameworks do. I think removing the module `Servant` from the package `servant-server` could help drive that point across.

So ideally I think that
- the package `servant` would contain the module `Servant`,
- the package `servant-server` would contain the module `Servant.Server` and
- the package `servant-client` would contain the module `Servant.Client`.

There's of course the argument that by now it's too expensive to change this. Not sure what I think of that argument myself.

**Comment by 3noch** [comment]
It will only get more expensive from here on out. ;)

**Comment by jkarni** [comment]
I've voiced a similar opinion to @soenkehahn 's before. I don't feel strongly about whether it's too late to make `Servant` come from `servant`, but if we don't (because of backwards compatibility/confusion), an alternative would be to have a new package, `servant-kitchensink`, that re-exports the most important functionality from the core packages under `Servant`. Still not quite backwards-compatible, but upgrading would only be a small change in the cabal file.

**Comment by soenkehahn** [comment]
By now I think we should move `Servant` to `servant`. (Using capitalization to distinguish modules from packages now.) `Servant.Server` (from `servant-server`) should be changed to export everything that the current `Servant` (from `servant-server`) exports, so it'll be a drop in replacement. If it doesn't do that already. The new `Servant` (then to be in `servant`) should export everything one commonly needs from `servant`. (I guess that will be the same that is currently exported by `Servant.API`.) It's a breaking change, but it's very easy to fix. (Just import `Servant.Server` instead of `Servant`.)

We could remove `Servant` in one release and then add it back (into `servant`) in the next. Maybe that would make it a bit easier to update projects. Or we could just make the switch at once. Which is what I would prefer, if I were to implement this. Because of laziness. :)

(Again, lots of PR scope creep, and useful discussions. So I'd like to point out that this issue is still about re-exporting `Application` from `Servant.Server` and `Server`. And that doesn't seem to be controversial.)

**Comment by kosmikus** [comment]
I think we are still in a phase where we can and should break things if we think they lead to an overall better design, so I don't have a big problem with changing the role and location of the `Servant` module.

Removing it from `servant-server` and encouraging to use `Servant.Server` instead seems like an obvious choice to me. I also don't see a problem with re-exporting the Servant API combinators from `Servant.Server`, so that for general server applications, importing just `Servant.Server` would be enough.

I'm somewhat less convinced (but also not opposed) that we should introduce `Servant` in the `servant` instead. In any case, I'd like to keep `Servant.API` around for a long time, because that is a more descriptive name. (FWIW, I wouldn't even mind renaming the `servant` package to `servant-api`.)

I'm against introducing `servant-kitchensink` or `servant-prelude`. This will just encourage people to write applications that depend on more packages than they actually need.

And yes, re-exporting `Application` is still ok with me.

**Comment by jkarni** [comment]
> I'm against introducing servant-kitchensink or servant-prelude. This will just encourage people to write applications that depend on more packages than they actually need.

Is that so bad? Not great for libraries, perhaps, but the end-user is just writing an application.

**Comment by jkarni** [comment]
Done in #505. #275 is probably a sensible place to continue discussion about module/package organization.
