### ISSUE TITLE
Cookie/SetCookie combinators - proper cookies support

### ISSUE THREAD

**Issue by dredozubov** [haskell-servant/servant#468]
I'm creating this issue to have a long-term resource for discussing design space for this particular problem. Afaik the main stumbling point to this is the absence of `SetCookie` combinator and all the plumbing to make it work. I had a discussion on this topic with @alpmestan on irc and want to highlight some points that i found important:
1. For getting cookies, it should be consistent with the rest of the combinators. The closest combinator is `Header`, so the semantic should be similar.
2. Setting cookies(and response headers in general - please correct me if i'm wrong) brings something to the table - handler return type is not dictated by the type parameter from the `Verb` combinators alone. It makes sense to have something like `(a, ResponseContext)` instead of `a` for the internal response type. Another solution would be to have a `StateT ResponseContext` on top of the handler monad stack, but it feels implicit and not servant-y at all, although it'll enable servant to sustain compatibility with previous versions in that sense and arguably will be easier to implement.
3. I think that getting cookies should be first-class in servant API, because cookies are somewhat special - they have key/value structure corresponding to RFC and it's impossible to unset something in the user browser, that's why it's important for them to be as explicit as possible in an API. This is the reason why i dislike the "we already have `Header` combinator" arguments.
4. It would be nice to integrate cookies/headers with generalized auth. e.g. `Cookie "secret-session" Session :> AuthProtected "cookie-based" :> ...`. Currently, generalized auth works on WAI request, so it can be made more explicit. I think it makes sense to change the type of auth handler from `AuthHandler Request a` to `Session -> AuthHandler a`(or `Session -> AuthHandler Request a` to have an escape hatch for the testing/adoption period). Similarly, `Session ->` should be appended to the handler type as well.

I'm experimenting on this right now and to be frank it's quite bumpy. Any thoughts?

**Comment by jkarni** [comment]
There should be, I think, only one combinator that does both getting and setting of cookies (the latter probably with something like `tweakResponse`). Furthermore, I'd think that it should also be integrated with auth, in that it should be possible to specify, with that single combinator, that if there is no cookie there should be a redirect to a login page (for example). 

I don't think this could be done *just* with [AuthProtect](https://github.com/haskell-servant/servant/blob/15143cc9008d3a861cfa2cd054f212da964fd9de/servant-server/src/Servant/Server/Experimental/Auth.hs#L57) as it currently stands, since there isn't a way of modifying the response. But if we simply add a new field there for that, it seems like enough?

So ultimately I think I'd like to see the API just look something like `AuthProtected (Cookie ...) :> .. `.

**Comment by alpmestan** [comment]
@jkarni How about the setting cookie side, i.e in the response?

**Comment by jkarni** [comment]
See `servant-auth` and `servant-auth-cookie`. Closing since there's nothing more to do here, but feel free to re-open if you disagree.

**Comment by kccqzy** [comment]
@jkarni I don't really agree with your decision to close this. The `servant-auth-cookie` is just for "authentication via encrypted client-side cookies" which actually conflates authentication and cookies. What about other use cases of cookies that are unrelated to authentication? IMO, we should have proper combinators for extracting cookie values and setting them.

**Comment by alpmestan** [comment]
This is a fair argument. I definitely think there's room for making the whole story around cookies nicer. We might even be able to "inject" that problem into the work done in #841, and see if the story can be made nicer there.
