### ISSUE TITLE
Update 'client in 5 minutes' tutorial

### ISSUE THREAD

**Issue by tim-millar** [haskell-servant/servant#483]
Presently, the code from the tutorial [Write a client library for any web API in 5 minutes](https://haskell-servant.github.io/client-in-5-minutes.html) is broken, at least for some versions of servant-client. It would be good if the code could be updated (to make it version agnostic), the version dependencies made explicit, or the tutorial pulled or flagged as deprecated if you no longer wish to support it. The tutorial also references a directory in the project's GH repo - `servant-examples/hackage` - that no longer exists.

I recently became interested in Servant. Google brought me to the github pages site, and the 'client in 5 minutes' tutorial was the first that caught my eye. I created a project directory on my system using stack, and copied the code over as I read the tutorial. When it came to build the project, Stack threw errors, because the function `run` was not in scope (I am using LTS 5.13, which uses servant-client-0.4.4.7). I tried to visit the referenced examples folder at the project's GH site to look at the source, but the folder did not exist.

After asking in the #servant IRC channel, I discovered that some versions of servant-client are no longer supported, hence the tutorial itself is somewhat out of date. I also discovered that the code will run if the two references to `run` are simply deleted.

As it stands the tutorial is confusing. It is either short of some essential information (such as version dependencies), the code contains a bug (calls to a non-existent and superfluous function), or it is not quite fit for purpose and readers should be warned on the page that it may not compile as the project no longer supports it. (Although there is a warning at the top of the home page, it is not clear how that relates to the individual tutorials linked beneath.)

**Comment by kosmikus** [comment]
I think that in general, we need to do a better job in pointing users to the "right" documentation. As long as pages are up, they should probably have an indication what version of servant they are intended for.

I can identify at least the following problems that I think are all worth fixing:

- http://haskell-servant.readthedocs.org/en/stable/ does not indicate what version it is for on the front page. Also, it's not clear what you would do / where you would go if you wanted documentation for an older version of servant.

- Users will still use servant-0.4 for a while to come, because that's the version in both the current LTS and Stackage Nightly snapshots. (Why is Nightly not using 0.7, btw?) But it's unclear right now where to find documentation for 0.4.

- While http://haskell-servant.github.io/ and http://haskell-servant.github.io/tutorial/ include a warning that they're not for the latest version of servant, several other pages underneath do not. But there are lots of direct links from elsewhere on the web.

- The code referenced in this issue does indeed run neither with 0.4 nor with 0.7, and refers to the examples directory which has been removed.

**Comment by jkarni** [comment]
>(Why is Nightly not using 0.7, btw?) 

Issue for upgrading to 0.5: https://github.com/fpco/stackage/issues/1290

> Also, it's not clear what you would do / where you would go if you wanted documentation for an older version of servant.

As in you think the dropdown at the bottom left is not prominent enough?

> The code referenced in this issue does indeed run neither with 0.4 nor with 0.7, and refers to the examples directory which has been removed.

Yeah, a lot of @soenkehahn 's work with the tutorial was getting it to compile since there were known issues. We could try to backport them to 0.4, but likely in `readthedocs` too. I personally think http://haskell-servant.github.io/ should just be mentioned as deprecated.

**Comment by kosmikus** [comment]
> As in you think the dropdown at the bottom left is not prominent enough?

No, at least not for me. I probably wouldn't ever have noticed if you hadn't mentioned it just now. I think it would already be an improvement if it said `version: 0.7` rather than `v: stable`. But it could also be more prominent. Of course, I guess this is a general readthedocs thing, so if you know how it works once, it's obvious from then on.

**Comment by jkarni** [comment]
We do have control over the HTML. But that's not something I'm great at messing around with (and it'd also mean deviating from the common RTD format).

**Comment by jkarni** [comment]
All of @kosmikus 's points except `stable` mentioning the version number have been addressed, I believe. Closing. If someone thinks trying to figure out how to get the version number to display in RTD `stable` is worth the time, please open another, more specific, issue.
