### ISSUE TITLE
Question: can I access raw request data in a `Handler`?

### ISSUE THREAD

**Issue by akisystems** [haskell-servant/servant#528]
I've been looking over other issues that talk about similar scenarios, but I haven't been able to conclude on it.

In a `Handler`, I wish to be able to access the raw request information: headers such as `X-Forwarded-For`, `Referrer`, but it is not clear from the documentation how I might go about this. 

Would anyone be able to point me in the right direction please?

Thanks for such an excellent API/library, I hope I can contribute back some day.

**Comment by jkarni** [comment]
Hi,

  The usual way is to add 'Header "X-Forwarded-For" Text' to the sub-api
that expects this header:

> type MyServer = Post '[JSON] Int :<|> Header "X-Forwarded-For" Text :>
Post '[JSON] Text
>
> myServer :: Server MyServer
> myServer = endpoint1 :<|> endpoint2
>    where
>      endpoint1 = return 5
>      endpoint2 :: Maybe Text -> Handler Text
>      endpoint2 Nothing = ""
>      endpoint2 (Just x) = x

The handler or handlers corresponding to the sub API that mentions the
'Header' will then receive a Nothing if the header is not present in the
request, or cannot be decoded into the mentioned type (in this case, Text),
and otherwise Just the value of the decoded header.

In essence, the idea is very much like ReqBody.

Other aspects of the request (besides headers) similarly have their own
combinators. See the hackage documentation for the servant package [0] for
a comprehensive list.


I hope that answers the question - if not, let us know!

Regards,
  Julian

[0] https://hackage.haskell.org/package/servant

**Comment by akisystems** [comment]
Thanks, that's perfect. As sod's law dictates, I found [this documentation page](https://hackage.haskell.org/package/servant-0.7.1/docs/Servant-API-Header.html) whilst searching again after asking the original question. It of course backs up what you've posted above. Is this covered in the (excellent) tutorial on read-the-docs? If not, I'll happily contribute some text towards it.

**Comment by alpmestan** [comment]
Header extraction is mentionned here and there on [this page](http://haskell-servant.readthedocs.io/en/stable/tutorial/Server.html?highlight=header) but if you feel this is not enough, we would gladly accept to the tutorial :)
