### ISSUE TITLE
Add dependency bounds

### ISSUE THREAD

**Issue by phadej** [haskell-servant/servant#534]
`http-client` issue is a good example why we should have them.

I can make a PR adding them, with lower-bounds from say *Stackage lts-2.22*, and upper-bounds allowing current major versions (if they do work, of course).

**Comment by soenkehahn** [comment]
I'm against adding preemptive upper bounds. While the situation with `http-client-0.5` is a good example for when preemptive upper bounds would be nice, in general I think *not* having upper bounds is the better trade-off.

cc: @haskell-servant/maintainers

**Comment by jkarni** [comment]
@soenkehahn why do you think so? As I see it, with stackage we get told pretty soon whether our upper bounds are ruling out some new version, and without them not only do things sometimes break, but also they remain broken for a while unless we (often @phadej ) painfully manually add upper bounds retrospectively to versions already on hackage.

**Comment by soenkehahn** [comment]
- Having to bump preemptive upper bounds causes additional work.
- I don't really care that much about these broken versions on hackage as long as the newest versions of dependencies are supported. So in the case of the `http-client-0.5` breakage I think we should strive for fixing it fast and uploading a new version to hackage. So that after a `cabal update` it'll build with the newer `http-client`. (And for existing projects I'm using pinned down dependencies, so I won't get a newer version of `http-client` without asking for it.)
- I always felt that compilation errors that are caused by new versions of dependencies are quite easy to understand and work around. (Much easier than the error messages by cabal's constraint solver in case it can't find a valid install plan, for example.)

But I'm not dogmatic about this. If most `servant` maintainers want to add upper bounds I'm perfectly fine with that.

**Comment by soenkehahn** [comment]
Just talked about this with @jkarni. We're planning to cherry-pick a0d5ed9aea10757caafa7d9654cb6f912d75a350 from #538 which adds upper bounds. Thanks @phadej!

**Comment by soenkehahn** [comment]
Here's the PR: #546.

**Comment by soenkehahn** [comment]
Done in #546.
