### ISSUE TITLE
Add a quasi quoter for servant route definition. 

### ISSUE THREAD

**Issue by sdemos** [haskell-servant/servant#55]
The version on hackage still has it, but it seems to have been taken out of the repository in commit 5470297bdc8f8c81dbca399f492b4e198f34af2e. Having the routes defined in a quasi quoter makes the route definition look much more natural, while still giving you the advantages of servant. 

Also, it would be cool if the new incarnation of the quasi quoter could also generate the routing function and not just the routing type, by providing it the name of haskell functions to use. I would imagine you might be able to use that to automatically derive the types of the routes as well, which would be cool.

**Comment by jkarni** [comment]
This might be a good place for discussing syntax. I was thinking of something like

```
method       (path | queryparams | matrixparams | ...)*        return-val
     (name: val)*
```
e.g.:
```
POST         /person                  Person
    Request: Name
    Accept: JSON, XML
    Content-Type: JSON, PlainText
    Headers: (Location, Link), (ETag, Text)
```

Where anyone can register a parser into a `Map String Parser`, where the string key gets used to match against e.g. `Request` and `Accept`, and `Parser` takes the value of that field, and produces a type. (The previous version wasn't extensible, so if you added a new combinator, you couldn't use QQ for it.)

That's what I more or less got working.  But there are questions, such as: can you apply things over multiple handlers, as you can with the non-QQ syntax? Should you be able to specify the name of the handler in the QQ, so you don't have to do the `:<|>` dance? What about client functions? Should there be a first section for specifying e.g. what name the type synonym of the API takes? (Previously we only generated the type, so it wasn't a `Dec` output, and you could just associated it with a type. It seems to me like that's not ideal.)

Thoughts anyone?

**Comment by s9gf4ult** [comment]
Why not [RAML](http://raml.org/)? I understand that to support all `RAML` features `servant` should become much more complex (if it is posible to express RAML in types) but `RAML` already has client libraries for Python, Javascript and other languages as well as documentation generator. It would be just awesome to have such a tool for Haskell.

**Comment by alpmestan** [comment]
You can open an issue for *RAML* if you want. It is most likely possible to export servant's API types into *RAML*, we just need someone interested in working on that.

**Comment by s9gf4ult** [comment]
It is already opened issue for [Blueprint](https://github.com/haskell-servant/servant/issues/35). Can `RAML` and `Blueprint` exist simultaneously in `servant`?

**Comment by alpmestan** [comment]
Yes. I actually would suggest having a package for interpretation in general. *servant-server* for writing webservers, *servant-client* for client functions and so on. Well, why not have *servant-blueprint* and *servant-raml* packages if some servant users want to target these description languages? No need to provide this feature in the core package.

**Comment by jkarni** [comment]
I would rather not make the QuasiQuoter itself look like either RAML or Blueprint - these are not nearly as extensible and flexible as Servant's API types, after all, and would tie us to formats we don't control. But *generating* RAML and Blueprint (as requested in #35, and much like `servant-docs` ) is a good idea.

**Comment by s9gf4ult** [comment]
RAML includes json schemas for response description. I dont know what is more logical, generate json schema from haskell's ADT (which `ToJSON` instance may not match to ADT structure) or to generate Haskell's ADT from RAML's json shcema with  `ToJSON`/`FromJSON` instances which always match the schema.

I tend to generate some trivial code from `RAML` description using `TH`.

**Comment by jkarni** [comment]
> I dont know what is more logical, generate json schema from haskell's ADT (which ToJSON instance may not match to ADT structure) 

This is a good point, but it's specific to `aeson`. The solution may be to just use/write a different library (e.g. our still-born [Cretheus](https://github.com/haskell-servant/cretheus) which I now think is not at all the right approach).

> or to generate Haskell's ADT from RAML's json shcema with ToJSON/FromJSON instances which always match the schema.

No, they don't match. The problem is the same in both directions. If I have an extra record that's not explicitly in the json schema for the request/response, this will not be reflected in the datatype when you generate it from the schema. You'll thus have to resort to intermediate types. Switching away from `aeson` sounds like a better compromise to me.

These points are also very JSON-centric. I don't think the (main) QQ should be tied to or optimized for JSON. If someone else wants to write a different QQ that is, that's of course very welcome.

I also still can't see how we could use RAML to generate arbitrary servant combinators without basically moving away from standard RAML altogether. There's a very good story outlined above about how to allow people to add combinators and corresponding QQ parsing (which was actually at some point implemented in a [proof-of-concept way](https://github.com/haskell-servant/servant/commits/jkarni/flexible-qq)); I don't see how that would work for RAML (but would be glad to be corrected).

Finally, I also think the proposed QQ is significantly more readable than RAML. 

Again, none of this is to say that I don't think *generating* RAML isn't a good idea.

**Comment by fizruk** [comment]
Is this issue still relevant?

FWIW, I don't think quasi quotation buys us much. `servant` APIs are already rather compact and self-descriptive. Trying to compress it just a little bit more will result in lots of TH code we would have to maintain while I am not sure many people would want to use it.

So, unless there is a pretty good reason for QQ, I am strongly :-1: here.

**Comment by jkarni** [comment]
I think we can close for now. Maybe when servant hits 1.0, and we decide to start focusing on being friendly to Haskell beginners, we can rethink.
