### ISSUE TITLE
Move ServerT into the core servant package

### ISSUE THREAD

**Issue by ElvishJerricco** [haskell-servant/servant#560]
Currently, `ServerT` is an associated type in the `HasServer` class. But it's potentially quite useful outside of servers. For instance, my [`servant-router`](https://github.com/ElvishJerricco/servant-router) package could use `ServerT` in the `HasRouter` class. But since it can't depend on `servant-server` (in order to compile for GHCJS), it doesn't have access to it, so instead it just replicates the type family. By moving `ServerT` into a type family outside of the class and into some package in the core `servant` package, `servant-router` (and any other potential libraries) could use it without duplicating code.

Sidenote: I can't help but feel that `servant-router` can be abstracted into something that `servant-server` could use in place of `HasServer`. Main idea being that client side routing and server side serving are similar up to the point of server-specific things like authentication and request bodies. Haven't put much thought into this yet though.

**Comment by alpmestan** [comment]
Little note: this would be a breaking change. Can you describe how is it that you would use `ServerT` in `HasRouter`?

**Comment by ElvishJerricco** [comment]
`HasRouter` would probably become something of this sort:

```haskell
class HasRouter layout a where
  route :: Proxy layout -> Proxy m -> Proxy a -> ServerT layout m -> Router m a
```

Or something to that effect. `constHandler` would be moved into its own class (preferably residing in the core `servant` package, so it can be used outside of `servant-router`)

```haskell
class HasConstHandler layout a where
  constHandler :: Monad m => Proxy layout -> Proxy m -> a -> ServerT layout m
```

**Comment by ElvishJerricco** [comment]
[Here's](https://github.com/ElvishJerricco/servant-router/tree/servert) a rough draft of how `servant-router` might be changed to adopt this change.

**Comment by alpmestan** [comment]
Interesting. To be honest, that's not a use case I had anticipated, but it does sound like we ought to help here. I'd be in favor on making this breaking change. What do others think?

**Comment by jkarni** [comment]
> Sidenote: I can't help but feel that servant-router can be abstracted into something that servant-server could use in place of HasServer. Main idea being that client side routing and server side serving are similar up to the point of server-specific things like authentication and request bodies. Haven't put much thought into this yet though.

I'm curious about this. We discussed a little the idea that there could be lenses that enforce the relationship between client and server implementations, and simplify them into one. But capturing that seemed a little subtle. If you have ideas, I'm very interested.

Re: the main point. `ServerT` and `Client` *almost* only differ in the monad, so all three could use the same type family. But not quite - `Vault` is a counter-example. Because this is the case - because the type class really is `server` specific, I'd prefer to keep things as is. Why can't `servant-router` use `Client`?

**Comment by ElvishJerricco** [comment]
Well for one thing, depending on `servant-client` has the same problem as depending on `servant-server` in a ghcjs application; the `IO` code baked in is irrelevant, and fails to compile.

I think `Vault` is the best example of the biggest problem with trying to unify all these things. The first solution I can think of is a sort of type level context.

```haskell
type MyApi context = Vault' context :> "root" :> Get '[JSON] Person

data Vault' a
data ServerContext
data ClientContext

-- Changing name of `ServerT` to more general `HandlerT`
instance HasHandlerT api => HasHandlerT (Vault' ServerContext :> api) where
  type HandlerT (Vault' ServerContext) m = Vault -> HandlerT api m

instance HasHandlerT api => HasHandlerT (Vault' ClientContext :> api) where
  type HandlerT (Vault' ClientContext) m = HandlerT api m
```

The point being, api components that produce different handler types for different contexts should indicate that in their type families. This way `HandlerT (MyApi ServerContext) m` looks like `Vault -> m Person`, and `HandlerT (MyApi ClientContext) m` looks like `m Person`.

By separating apis by context using a type parameter, each of these different implementations can be separated. Each context type is defined in its respective package; `ClientContext` and its associated instances are defined in `servant-client`, and `ServerContext` and its associated instances are defined in `servant-server`.

As for the idea of sort of merging the logic of a client side router with the server side router, I think if we simplify `HasServer` for the purposes of brainstorming, throwing performance concerns out the window for now, you can sort of add request and response types to the class.

```
class HasHandlerT api where
  type HandlerT api m :: *

class HasHandlerT api => HasRouter api req res where
  route :: Monad m => Proxy api -> req -> HandlerT api m -> m res

data Vault' a
data FrontEndRoutingContext
data ServerContext

-- Client side?
instance HasHandlerT api => HasHandlerT (Vault' FrontEndRoutingContext :> api) where
  type HandlerT (Vault' FrontEndRoutingContext :> api) m = HandlerT api m

data Location = Location { path :: [String], query :: [(String, String)] }
instance HasRouter api Location res
         => HasRouter (Vault' FrontEndRoutingContext :> api)
                      Location
                      res where
  route _ = route (Proxy :: Proxy api)

-- Server side?
instance HasHandlerT api => HasHandlerT (Vault' ServerContext :> api) where
  type HandlerT (Vault' ServerContext :> api) m = Vault -> HandlerT api m

data Request = Request { loc :: Location, reqBody :: ByteString, headers :: [Header], vault :: Vault }
instance HasRouter api Request res
         => HasRouter (Vault' ServerContext :> api)
                      Request
                      res where
  route _ req handler = route (Proxy :: Proxy api) req (handler $ vault req)
```

This is a really rough idea (the above probably doesn't even compile without some fun-deps). But maybe it's close enough that it could be made into something real? I think it definitely illustrates that it's possible to have the routing logic shared between *most* things - especially if you use classy lenses for stuff like the path and query.

**Comment by soenkehahn** [comment]
I find the idea of having a more abstract interpretation of `servant` APIs very interesting. And then having more concrete use-cases implemented on top of these more abstract interpretations. I've been thinking about something like this for `servant-client` for some time now.

But I'd like to speak out strongly in favor of implementing these things as separate packages for now. To allow for more freedom in experimentation and to gather some experience in how useful they turn out to be. @ElvishJerricco: Once we have a good and proven implementation for a more abstract server-like interpretation in a separate package, we could switch `servant-server` over to use that one. (Same goes for `servant-client`, although there I'm thinking that it might even be good to just write a replacement for `servant-client` from scratch.)

One other thing that may be relevant when experimenting with all this: You can **compile** `servant-server` with `ghcjs` just fine. It's just that some of the functions will crash at runtime, since they call out to c libraries. (Unless something changed in `ghcjs`.) So to experiment with the type-level stuff of `servant-server` in `ghcjs` you should be fine.

I'd like to close this issue as `wontfix`.

**Comment by jkarni** [comment]
I'm also in favor of closing. I think the easier solution is to just get `servant-client` working with GHCJS already (so `servant-router` can depend on it).

**Comment by ElvishJerricco** [comment]
Getting servant-client working with GHCJS means using a lot of `-XCPP` macros to write the code twice in one package. Unless it ended up using some `MonadHttp` class to abstractly request HTTP capabilities without requiring implementation details, then having a different package with a different implementation of that class for each client (which isn't a bad solution).

Anyway, I guess I'll look into writing some packages to demonstrate these sorts of changes.

**Comment by jkarni** [comment]
@ElvishJerricco @soenkehahn already did the work to get GHCJS working on a branch. I think the only reason we haven't merged it yet is because we haven't gotten CI for it to work.
