### ISSUE TITLE
Stream response in servant-client

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell-servant/servant#604]
Is there a way to define an API that streams responses (i.e. interops with conduit, streaming-commons, or something)? I don't know all of the ways HTTP can stream responses incrementally, but at least in this simple API I'm interacting with, one of the endpoints returns a `Transfer-Encoding: chunked` header.

However, typing this return value as `[Text]` is obviously wrong, and I couldn't get `Raw` to work either (the derived client returns the response as a single, fully-evaluated lazy `ByteString` via `Network.HTTP.Client.httpLbs`.

**Comment by soenkehahn** [comment]
There's currently no way to write neither a server nor a client that uses `conduit` or some streaming library for request or response bodies. Generally I also think that this probably shouldn't be represented in the api type. Because whether a server or client uses streaming is something that is not important to the other  side and therefore shouldn't leak through the api. (Any opinions on this?)

I take it that you're talking about the client-side. I guess the easiest way to make this work, is this:

1) Write a test that makes sure that clients can stream request and response bodies as lazy `Text` (and maybe lazy `ByteString`s).
2) If they fail, fix them.
3) Turn the lazy `Text`s into a `conduit` in your client code.

**Comment by jtdaugherty** [comment]
I'm working on a project where I'd love to be able to do response streaming server-side (i.e. I don't care what the client does, I just know I need to be able to send out response chunks as they become available). I don't need this to be specified in the API, but I'd prefer to have some way of getting low-level access to the response machinery so I don't have to use `conduit`. Are there any options for doing this?

**Comment by soenkehahn** [comment]
@jtdaugherty: Thanks for your feedback on whether this should be in the api or not.

Unfortunately streaming response bodies is not really supported in `servant-server` currently. I've opened #612 as a first step towards what you want. (Since this ticket is about `servant-client`.)

**Comment by edsko** [comment]
> There's currently no way to write neither a server nor a client that uses conduit or some streaming library for request or response bodies. 

@soenkehahn this is not actually true. See my examples at #271.

**Comment by soenkehahn** [comment]
@edsko: Thanks for the examples.

Personally I wouldn't want to call this 'supported' as long as we don't have tests for this. Since refactorings could always break it in a future version. (I'll update #612.)

**Comment by domenkozar** [comment]
Should be possible with https://github.com/plow-technologies/servant-streaming

**Comment by domenkozar** [comment]
This was released part of Servant 0.15

**Comment by domenkozar** [comment]
This is now part of Servant.
