### ISSUE TITLE
Enter exhausts simplifier ticks when used with large-ish API type

### ISSUE THREAD

**Issue by phadej** [haskell-servant/servant#749]
See https://github.com/haskell-servant/servant/issues/734 for more details

**Comment by phadej** [comment]
@fizruk could you try to reorder `Entered` clauses, whether you'll still need simplifier ticks:

```diff
--- a/servant/src/Servant/Utils/Enter.hs
+++ b/servant/src/Servant/Utils/Enter.hs
@@ -28,9 +28,9 @@ import           Prelude.Compat
 import           Servant.API
 
 type family Entered m n api where
-    Entered m n (m a)            = n a
     Entered m n (a -> api)       = a -> Entered m n api
     Entered m n (api1 :<|> api2) = Entered m n api1 :<|> Entered m n api2
+    Entered m n (m a)            = n a
     Entered m n (Tagged m a)     = Tagged n a
 
 class ( Entered m n typ ~ ret
@@ -70,7 +70,12 @@ instance
 
 -- ** Useful instances
 
-instance Enter (m a) m n (n a) where
+instance 
+    ( Entered m n (m a) ~ n a
+    , Entered n m (n a) ~ m a
+    )
+    => Enter (m a) m n (n a)
+  where
     enter (NT f) = f
 
 -- | Like `lift`.
```

Also *maybe* adding of constraints to `Enter (m a) m n (n a)` instance might help already.

**Comment by phadej** [comment]
```diff
-    => Enter typ m n ret
+    => Enter typ m n ret | typ m n -> ret, ret m n -> typ
```

might help too

**Comment by paf31** [comment]
I ran into this issue today, and wrote this class to replace `enter` and get around the issue:

```haskell
-- | APIs whose server types support a hoisting operation
class HasHoist (api :: *) where
  hoistApi 
    :: forall m n
     . (forall a. m a -> n a)
    -> ServerT api m
    -> ServerT api n

instance HasHoist EmptyAPI where
  hoistApi nt = retag

instance (HasHoist a, HasHoist b) => HasHoist (a :<|> b) where
  hoistApi nt (a :<|> b) = hoistApi @a nt a :<|> hoistApi @b nt b

instance HasHoist (Verb m s f (a :: *)) where
  hoistApi nt s = nt @a s

instance HasHoist api => HasHoist ((s :: Symbol) :> api) where
  hoistApi nt = hoistApi @api nt

instance HasHoist api => HasHoist (Capture s (a :: *) :> api) where
  hoistApi nt f = hoistApi @api nt . f

-- ... and so on
```

Is solves the issue for our purposes, but maybe something like this could be generally useful. Would you take a PR?

**Comment by phadej** [comment]
`HasHoist` has a drawback of needing an instance for each API combinator. OTOH it's definitely less magic / ad-hoc than `Enter`.

I assume that signature needs `AllowAmbigiousTypes` extension? I'd rather prefer taking a `Proxy api` (we'd like to support pre-GHC-8.0).

I'm neutral about addition, if others like it, we can have it. @haskell-servant/maintainers?

- Naming? `HasHoist` & `hoistApi` is more obvious than `enter`. 
- Would we still need `enter` as defined currently?

**Comment by paf31** [comment]
Yes, without a proxy it is ambiguous.

Another option is to move it to `HasServer`. Saying that `ServerT` is natural in the choice of monad seems sensible to me, but I don't know enough corner cases to say for sure, and obviously it's a breaking change.

**Comment by endgame** [comment]
I have also run into this bug. After moving to 0.11 we had incredibly long compile times in the module that applies `enter` across the API. Trying to manually push the `enter` down into each module's API implementation caused simplifier tick exhaustion, but we were able to make it compile (and do so much more quickly) by rolling our own `HasHoist` based on the comment above.

Unfortunately it's a proprietary code base or I'd share samples.

**Comment by alpmestan** [comment]
No need to share it necessarily, we've got all the data we need here I think. I don't like `enter`, this `HasHoist` class at least can make life easier for everyone, so we can give it a shot. I'm still waiting for a nice solution for manipulating `:<|>`-separated stuffs, but until then, I'm willing to replace enter by hoistApi, assuming this all gets documented, tested and what not :)

@paf31 Thanks for this suggestion, by the way.

**Comment by dredozubov** [comment]
I'm having the same issue. I'm wondering if we can just get rid of `enter`, I don't see a lot of usefulness in having a natural transformation `m a -> n a` where `n` is `ExceptT IO`, `IO` has an ability to throw and catch exceptions and `ExceptT` transformers can be dropped. What was the reasoning behind it? Do we need to keep it?

**Comment by alpmestan** [comment]
@dredozubov The next release will include `hoistServer`, a replacement for `enter` that won't cause any more hussle than server handlers do in general, as it will be a method of `HasServer`. You can already see it (and use it) in the `master` branch. The PR is quite recent, you might want to look it up.

**Comment by dredozubov** [comment]
@alpmestan my point is: it's possible to get rid of hoisting and natural transformations altogether, all we need is `IO`

**Comment by saurabhnanda** [comment]
My vote for simplifying this monad/type jigsaw. I'm not sure if any of this is related to #812

**Comment by saurabhnanda** [comment]
I'm not sure if there is any valid/widespread use-case for writing a webapp where the base monad is not IO. So, if that one assumption can make all this type-hackery go-away, then please, please do it.

**Comment by fizruk** [comment]
@dredozubov `IO` can do everything, for sure. That's not a good reason to abandon `ExceptT`.

Also, if you drop `ExceptT` and live `IO` you still need hoisting and natural transformations. They will just go to `IO` instead of `ExceptT ServantErr IO`. So I don't see how that would help.

Can you elaborate on what you're proposing?

**Comment by dredozubov** [comment]
@fizruk I'll try to explain. You can throw, catch and handle `ServantErr` in `IO` without `ExceptT ServantErr IO`(unless I miss something, that's why I'm asking about it). If we drop it, for the user it'll just boil down to transforming the handlers to `IO`, which you have to do anyway if you're writing a WAI app. I don't see how introducing mtl and forcing the user to write a natural transformation is benefitting the design in any way. It was bugging me for some time.

This change will change the api handlers code from `foo :<|> bar` to `unrollToIO foo :<|> unrolltoIO bar`. I find it much cleaner, you just need to follow the types.

**Comment by alpmestan** [comment]
I'm not keen _at all_ on making this arbitrary choice. There simply is no good reason to. _We_ should not decide what kind of monads _users_ should run their handlers in. servant has been designed so as to make as few such arbitrary decisions as possible, and it will stay that way. As a matter of fact, I've made pure functions available through a webservice before. Not at work, but that still qualifies. Sure, that's not the common case, but we don't want servant to handle just the common case and give up on everything else.

And please give a shot at `hoistServer` before rejecting it, pretty sure it will not cause problems in most if not all cases where enter was causing some :) That's actually the biggest argument I have, above the one from the first paragraph. Give it a shot, let us know if you encounter problems.

**Comment by alpmestan** [comment]
> This change will change the api handlers code from foo :<|> bar to unrollToIO foo :<|> unrolltoIO bar. I find it much cleaner, you just need to follow the types.

Well, you can already do this, except that the target monad is `Handler` instead of `IO`. You can already manually convert your handlers from some fancy monad to `Handler` by just having something like your `unrollToIO`. Not doing that by hand is exactly the purpose of `enter`/`hoistServer`, but you can do without of course!

**Comment by alpmestan** [comment]
Also, I'm even less keen on relying on unchecked exceptions instead of checked ones, for our "escape hatch" (throwing 3xx, 4xx etc).

**Comment by dredozubov** [comment]
I don't see what you mean by "arbitrary" here. Servant must conform to WAI interface, which forces us to provide an `IO` action. That's not arbitrary, that's given. I find `enter` more restrictive than helpful: let's say I have a pure function for one of the handlers(`handler1`), just as you've described, but I have to query DB to respond to other requests(`handler2`). If I use `enter`, I'm forced to make something compatible with both cases, which means I have to consume database connections and have IO in my monad transformer. Now I have to lift my `handler1` to `IO` to make it compatible with a natural transformation I supply in `enter`. What's the purpose of that? I'd argue that it actually makes me lose type-safety in some situations, rather that make it more safe. That's an arbitrary solution in my book. Also I've been told on multiple occasions that this aspect of servant is extremely frustrating for beginners and I can see why.

I'm not familiar with the current checked-exceptions situation, that may be a valid concern.

**Comment by fizruk** [comment]
@dredozubov 

> I don't see how introducing mtl and forcing the user to write a natural transformation is benefitting the design in any way.

`mtl` is not forced on you. You can have whatever you want, just convert it to `Handler` (which is `ExceptT ServantErr IO`) when you're done.

Natural transformations arise here naturally (no pun intended). Since the result type of each individual handler is different, but the context is the same. So you have to convert every `MyHandler a` to servant's `Handler a` or, as you propose `IO a`. That's what's your `unrollToIO` is about, isn't it?
But `unrollToIO` *is* exactly a natural transformation!

```
unrollToIO :: forall a. MyHandler a -> IO a
```

It's just not wrapped in a `NT` newtype.

> This change will change the api handlers code from foo :<|> bar to unrollToIO foo :<|> unrolltoIO bar. I find it much cleaner, you just need to follow the types.

As @alpmestan mentions — this is just applying hoist/enter manually, so you can do it right now, without any changes to `servant`.

**Comment by alpmestan** [comment]
By "checked exception", I simply meant `Either`/`ExceptT`.

Regarding the IO: sorry but I don't care what wai does. We have other backends, and could have even more. It also should not prevent me from specifying that all my handlers are pure, and then have servant turn that into a webservice with effectful actions happening all over the place to provide my pure functions with some input data. That's why I see `ServerT api MyMonad` as useful: my handlers use whatever `MyMonad` has, no more no less. If you just "unroll" each handler manually to the right target type then you can't as easily get such guarantees.

Also, again, you're talking a lot about `enter`, not about `hoistServer`. Please check it out.

**Comment by fizruk** [comment]
@dredozubov 

> let's say I have a pure function for one of the handlers(handler1), just as you've described, but I have to query DB to respond to other requests(handler2). If I use enter, I'm forced to make something compatible with both cases, which means I have to consume database connections and have IO in my monad transformer.

I think you misinterpret `enter` as an exclusively whole API transformation.
You're not forced to apply `enter` (or `hoistServer`) to your whole API. You can apply your `unrollToIO` natural transformation per endpoint (without using `enter`). Or you can apply `enter` to a  subAPI that requires DB access. Or both :)

**Comment by alpmestan** [comment]
And yes, a natural transformation is basically the fancy name for those functions that can take a `Monad1 a`  to a `Monad2 a` for any `a`, which is exactly what any "unrolling"-like function will do. But sometimes you don't really "unroll" but instead go from a given monad to a totally different one that has nothing or very little in common. And one the points I wanted to make was that `Handler` is the natural monad for servant-server right now, until we figure out better stories for redirects, error throwing etc we're stuck with something like `ExceptT`. We won't use exceptions for doing these things. But any user who's not writing a hello world will use his own monad stack where he or she can have all the desired features/guarantees/etc. Then, to turn these fancy handlers into something servant can, well, serve,  someone has to apply a function that goes from the fancy monad stack to `Handler`. Either on each handler manually, like in your `unrollToIO` example, or by simply specifying the function once and having something apply it for you to all handlers. `enter` was doing the latter rather poorly, while `hoistServer` (not release yet, available in `master`) will do it much, much better. I'm expecting much less confusion and type errors.

**Comment by phadej** [comment]
@fizruk could you try out `servant-server-0.12` `hoistServer`, how it works for you?

**Comment by jkarni** [comment]
Closing since `hoistServer` seems to be the solution. Please re-open if not.
