### ISSUE TITLE
[Servant-client] Documentation not converted to 0.4.0

### ISSUE THREAD

**Issue by PierreR** [haskell-servant/servant#75]
I am confused. [The front page example](https://github.com/haskell-servant/servant-client) has not be updated yet  (I can PR if needed) ?

I cannot compile it with `0.0.4`.

I am probably missing something because [the haddock](https://github.com/haskell-servant/servant-client/blob/master/src/Servant/Client.hs) would  be out of dated as well .... 

Can we still do `type MyApi = "books" :> Get [Book]` together with `type MyApi = "books" :> Get '[JSON] [Book]` ?

**Comment by alpmestan** [comment]
Err... That's terrible. I will update this shortly. Thanks for reporting it! Yeah now you have to specify `'[JSON]` (or you could define type synonyms to `Get` and friends if you're only interested in JSON).

**Comment by PierreR** [comment]
I would love an example that keeps the BookUrl in the signature of `getAllBooks` because it is an external parameter for me. For instance:
```
type MyApi = "books" :> Get '[JSON] [Book] -- GET /books
        :<|> "books" :> ReqBody Book :> Post '[JSON] Book -- POST /books

getAllBooks :: BaseUrl -> EitherT String IO [Book]
postNewBook :: Book -> BaseUrl -> EitherT String IO Book
-- 'client' allows you to produce operations to query an API from a client.
(getAllBooks :<|> postNewBook) = client myApi
```
It doesn't compile. There is probably an obvious trick to make it so (but I don't see it immediately)

**Comment by alpmestan** [comment]
Well, we actually changed it so that you don't have to give the `BaseUrl` argument to every single function since you're most likely targeting the same server. If you receive the host from somewhere at runtime, you can just derive your functions when you get it, e.g:

``` haskell
f :: IO ()
f = do
  baseurl <- getBaseUrlFromSomewhere
  (getAllBooks :<|> postNewBook) = client myApi baseurl
  -- ...
```

This may be a bit more annoying, but has to be balanced against having to pass the baseurl to each function =) Would you really rather pass baseurl to each function even if it's the same all along?

**Comment by PierreR** [comment]
Thanks. It all makes sense now ;-)
