### ISSUE TITLE
Option to ignore Content-Type checks for JSON-only APIs?

### ISSUE THREAD

**Issue by saurabhnanda** [haskell-servant/servant#817]
Is there any way to build a JSON-only API where the client is not forced to send `Content-type: application/json` with every request? Practical use-case: being able to simply type the URL in my browser and see the resulting JSON. Makes quick debugging a breeze!

**Comment by 3noch** [comment]
As a stopgap you could accept PlainText and just serialize the JSON on the way out.

**Comment by alpmestan** [comment]
@saurabhnanda You could very simply define your own JSON content type, as illustrated here: https://haskell-servant.readthedocs.io/en/stable/tutorial/Server.html#using-content-types-with-your-data-types

Hopefully this shows how _trivial_ a content type is in servant. So yeah, just define your own that does JSON encoding/decoding but "advertises" plaintext or whatever else you want. Let us know if things are still not clear after having read that section from the tutorial and feel free to close the issue otherwise :)

**Comment by saurabhnanda** [comment]
> Hopefully this shows how trivial a content type is in servant. So yeah, just define your own that does JSON encoding/decoding but "advertises" plaintext or whatever else you want. Let us know if things are still not clear after having read that section from the tutorial and feel free to close the issue otherwise :)

Thank you. This solves the problem 👍
