### ISSUE TITLE
Should it be possible to use PostNoContent without a NoContent response?

### ISSUE THREAD

**Issue by tekul** [haskell-servant/servant#828]
I had a bug in my code due to a misunderstanding of what `PostNoContent` was for. It was fixed by [this change](https://github.com/ThreeMinuteLearning/my3ml/commit/dcc1bc6e0c3873e134cac857268eb884ea06c1e8#diff-a6046668c5cf3818d5199d2ec792bd98L255). I wanted a POST request with an empty request body, but which returned an identifier string.

However, I found that my client was receiving an empty response, even though my server implementation was returning the identifier. It seems that servant automatically assumes a `NoContent` response type (which makes sense, now that I understand it) and ignores the value. Shouldn't the server implementation always have to return `NoContent` in this case?

**Comment by alpmestan** [comment]
@haskell-servant/maintainers Thoughts?

**Comment by fizruk** [comment]
I think in https://github.com/haskell-servant/servant/pull/276#r49136760 is the historical explanation for why there is a value type at all in `PostNoContent`.

Basically it's there to be able to provide `Headers` as in

```haskell
PostNoContent '[JSON] (Headers '[Header "X-Custom-Header" CustomData] NoContent)
```

### Potential solution 1

However, I think we can just provide a separate `PostNoContentWithHeaders`:

```haskell
-- | Internal.
-- @noContent@ should always be instantiated with a 'NoContent' type,
-- possibly wrapped in 'Headers'.
type PostNoContentInternal contentTypes noContent = Verb 'GET 204 contentTypes noContent

-- | 'POST' with 204 status code and no extra headers.
type PostNoContent contentTypes
  = PostNoContentInternal contentTypes NoContent

-- | 'POST' with 204 status code and custom headers.
type PostNoContentWithHeaders contentTypes headers
  = PostNoContentInternal contentTypes (Headers headers NoContent)
```

This might be not super elegant, but I think it should provide a cleaner user experience.

### Potential solution 2

Alternatively we could turn `PostNoContent` into a type family and use Custom Type Errors (for GHC 8):

```haskell
-- | Internal.
-- @noContent@ should be instantiated with a 'NoContent' type,
-- possibly wrapped in 'Headers'.
type PostNoContentInternal contentTypes noContent = Verb 'GET 204 contentTypes noContent

-- |
type family PostNoContent contentTypes noContent where
  PostNoContent contentTypes NoContent = PostNoContentInternal contentTypes NoContent
  PostNoContent contentTypes (Headers headers NoContent)
    = PostNoContentInternal contentTypes (Headers headers NoContent)
  PostNoContent contentTypes returnType = TypeError
    (    Text "Excepted NoContent or (Headers '[...] NoContent)"
    :$$: Text "but got" :<>: ShowType returnType
    :$$: Text "Note that you should not return any response when using 204 status code."
    :$$: Text "Doing so could lead to HTTP clients ignoring the response."
    :$$: Text "Consider using" :<>: ShowType Post
         :<>: "with a different status code instead."
    :$$: Text "If you know what you're doing, see " :<>: ShowType PostNoContentInternal
    )
```

Of course, we can generalise this for all `Verb`s with `NoContent`.

I prefer using custom type errors since
- it is almost backwards compatible
- it provides a better user experience with detailed explanation about what's happening.

**Comment by 3noch** [comment]
I like it!

**Comment by alpmestan** [comment]
I have to say the custom type errors are quite appealing here. But solution 1 prevents the problem by construction and is conceptually simpler to approach/understand, I think. So maybe I would give that one my vote, but I won't object to solution 2 being merged to be honest. I think that as long as this whole `NoContent` business is well-documented in the tutorial and haddocks, whichever solution we choose, users will be fine.

**Comment by 3noch** [comment]
Would another option be to have a version of `Headers` that doesn't take a payload type? E.g. `JustHeaders []` would be the most common response type in this case.

**Comment by fizruk** [comment]
@alpmestan I think we can provide both solutions :)

I like custom type errors approach because, honestly, I think this is something users are way more likely to read than servant documentation or tutorial. And they'll read it exactly if/when they face the problem!

That does not mean that proper haddocks and tutorials aren't needed, just that custom type errors might be more convenient for users than docs.

@3noch I'm not sure what you're suggesting :)
How would `OnlyHeaders` be different from this?

```haskell
-- | 'POST' with 204 status code and custom headers.
type PostNoContentWithHeaders contentTypes headers
  = PostNoContentInternal contentTypes (Headers headers NoContent)
```

### Potential solution 1(b)

There's also an option to apply `Headers` outside of `Verb`, to the whole API:

```haskell
type family AddHeaders headers api where
  AddHeaders headers (param :> sub) = param :> AddHeaders headers sub
  AddHeaders headers (left :<|> right) = AddHeaders headers left :<|> AddHeaders headers right
  AddHeaders headers (Verb method code contentTypes (Headers oldHeaders retType))
    = Verb method code contentTypes (Headers (headers ++ oldHeaders) retType)
  AddHeaders headers (Verb method code contentTypes retType)
    = Verb method code contentTypes (Headers headers retType)
```

Then instead of

```haskell
PostNoContentWithHeaders '[JSON] '[Header "X-Custom-Header" CustomData]
```

we'd have

```haskell
AddHeaders '[Header "X-Custom-Header" CustomData] (PostNoContent '[JSON])
```

**Comment by 3noch** [comment]
@fizruk I agree that the issue here is one that people will probably hit *while coding* (i.e. disconnected from docs). I certainly have! In that sense have immediate compiler feedback is very helpful. Granted, the correct-by-construction method has the benefit of not needing that feedback. So both make sense.

My idea was basically to have a response type that did not include a payload type. It's essentially the same as `PostNoContentWithHeaders` except that you don't change the verb:

```haskell
type Api = "api" :> PostNoContent '[JSON] (OnlyHeaders [])
```

Here you can't specify a payload type, so you can't get it wrong, just like `PostNoContentWithHeaders`. However, you don't need a new verb, which I think is slightly better. I can see wanting `OnlyHeaders` for other cases as well.

**Comment by fizruk** [comment]
A minor note: "correct-by-construction" methods in Servant sometimes make it very difficult to integrate with external APIs which are ill-designed. So we definitely need "wrong" methods to be exposed for that purpose.

@3noch I see what you mean now, thanks! Still, I think by default you don't want to mention headers (but maybe I'm wrong).

**Comment by tekul** [comment]
Thanks for all the replies :). I like the idea of using type errors to enforce the use of `NoContent`, and I don't really mind as long as it stops me from doing something broken one way or another. As a relatively new user though, it still seems a bit confusing that `PostNoContent` is then required at all - I'd probably ask why `PostNoContent '[JSON] NoContent` couldn't just be `Post  '[JSON] NoContent`. Is it a limitation of the type system, or just to allow the use of different status codes in the response?

**Comment by fizruk** [comment]
@tekul Thank you for filing an issue :)

`Post '[JSON] NoContent` uses `200` status code but `204` should be used for no content.
So you either use raw `Verb 'POST 204 '[JSON] NoContent` or use alias like `Post`, `PostCreated` or `PostNoContent` to avoid hardcoding codes.

**Comment by tswelsh** [comment]
I just ran into this issue when converting a route that returned `204` into one that returns `200` with some content. It didn't cause a serious problem but I was briefly confused about what was going on. In particular, the docs on [hackage](https://hackage.haskell.org/package/servant-0.12/docs/Servant-API-Verbs.html#g:6) don't say that the return type will be ignored with status code 204, and [readthedocs](http://haskell-servant.readthedocs.io/en/stable/tutorial/ApiType.html#capture) has the line
> `DeleteNoContent` specifies a `204` response code ... and `NoContent` says that the response will always be empty.

The last bit implied to me that the empty response is because we've specified `NoContent`, and return code and content are independent (I know that we shouldn't return content with `204` anyway but that's what it sounds like), when in fact the return type is ignored in this case and the emptiness comes from the `204` response code.

Not the worst thing in the world but it would be nice to see this being disallowed.

**Comment by winduptoy** [comment]
The documentation left me confused for a bit. There are numerous examples in the documentation that specify an API like...

```
type ProductsAPI =
       Get '[JSON] [Product]
  :<|> ReqBody '[JSON] Product :> PostNoContent
```

When trying to implement myself, I was getting the compile error:

```
Expecting two more arguments to ‘PostNoContent’
      Expected a type, but ‘PostNoContent’ has kind ‘[*] -> * -> *’
```

Should the docs be updated to the following? 

```
type ProductsAPI =
       Get '[JSON] [Product]
  :<|> ReqBody '[JSON] Product :> PostNoContent '[JSON] NoContent
```

**Comment by phadej** [comment]
@winduptoy which servant version you use?

In `servant-0.17` the `PostNoContent` alias was changed, you can see it e.g. in https://github.com/haskell-servant/servant/blob/5998429e8178c9e9cc58ec3cfdc4d92e0e9c2400/servant/src/Servant/Test/ComprehensiveAPI.hs#L67 

---

And it looks like that `servant-0.17` also fixes this issue, as we have the `VerbNoContent` now. Therefore I'm closing this issue

**Comment by winduptoy** [comment]
@phadej Yep, stack `lts-14.27` left me on `servant-0.16.2`. Thanks!

**Comment by nmtitov** [comment]
Snapshot `lts-15.6` also has only 0.16.2. I had to update `extra-deps`

```
extra-deps:
  - servant-0.17
  - servant-server-0.17
```
