### ISSUE TITLE
How to handle field selection

### ISSUE THREAD

**Issue by kanishka-azimi** [haskell-servant/servant#910]
I have some routes that use field selection (see below for an example) where query parameters dynamically select the shape of the JSON returned. How would you model this?

Example: "field selection" as demonstrated here (https://saipraveenblog.wordpress.com/2014/09/29/rest-api-best-practices/) and in other guides to HTTP APIs.

**Comment by jkarni** [comment]
The simplest way is to have the datatype your endpoints was returning, let's say `A`:

```haskell
data A = A
  { field1 :: Int
  , field2 :: Bool
  }
```

Now have a `Maybe` over all fields that can be selected or not:


```haskell
data A = A
  { field1 :: Maybe Int
  , field2 :: Maybe Bool
  }
```

Making sure the `ToJSON` instance has `omitNothingFields` set to True (or the corresponding behavior if written manually). 
And then have the endpoint take a capture of a `[String]`, and use that to decide which fields to set to `Just` and which to `Nothing`.

If you just have two or three of endpoints where this is happening, that's probably enough. Otherwise, there are improvements that would make this more convenient. To my mind the best would be to write a new combinator, `VerbWithFieldSelection`, which is an exact analog of `Verb`, but in case of JSON or "selectable" content-type, checks the query params for which fields to select, and does that on top of the `Value` that'd be returned. 

If you need more help with either of those, let us know!

**Comment by kanishka-azimi** [comment]
Great!

I will start with the suggestion. It's used in a bunch of places in my API, but I just want to get the API into Servant to start. I will reopen when I have reached a point where I want a more explicit implementation.

Consider documenting this somewhere in a servant cookbook.
