### ISSUE TITLE
Implement mapping over leaves of homogenous handlers

### ISSUE THREAD

**Issue by tysonzero** [haskell-servant/servant#932]
I am using an "isomorphic" framework called miso for web development, and one issue I am currently running into is that I need both the client and the server to be able to handle the same set of routes.

Currently this requires [doing the routing twice](https://github.com/dmjio/miso/issues/353), once in a way that Servant can handle, and once in a way that Miso can handle.

I unfortunately cannot just do it the way Servant likes and then convert it over on the Miso end, as Servant wants actually Html pages which cannot easily be transferred back into the app state that Miso needs. I also currently cannot just do it the way Miso likes and then convert it over on the Servant end, for basically the same reasons.

What would be ideal is if I could have the handlers all store a type of my choosing (i.e `AppState`) at their endpoints, and then for Miso apply a mapping function to convert `AppState` into `View a`, and then for Servant apply a mapping function to convert `AppState` into an Html page.

It would thus be ideal if there was a mapping function that applied `a -> b` to the leaves of all homogenous handlers. Just like what can currently be done with `hoistServer`, except operating on the entire leaves (both the monad and the type contained within the monad) instead of just the monad.

This will also most likely need two type families, one that adjusts the `api` appropriately by mapping over all the `()` endpoints (`LeafT`), and one that works just like `ServerT` but instead of taking in a `m :: * -> *`, it takes in an `a :: *` and converts all the `()` into `a`, rather than `m ()` which `ServerT` would (`HandlerT`).

You could then define an `api` and `handler` like follows:

```haskell
    type Routes = HomeRoute :<|> FooRoute :<|> BarRoute
    type HomeRoute = ()
    type FooRoute = "foo" :> ()
    type BarRoute = "bar" :> Capture "id" Int :> ()

    data AppState = Home | Foo | Bar Int

    handler :: HandlerT Routes AppState
    handler = Home :<|> Foo :<|> Bar
```

Which can be served from `Servant` like this:

```haskell
    server :: HandlerT Routes (Handler (Get '[HTML] Foo))
    server = mapLeaves (pure . HtmlPage . mainView) handler

    main :: IO ()
    main = serve (Proxy @(LeafT Routes (Get '[HTML] Foo))) server 
```

And from `Miso` like this:

```haskell
    main :: IO ()
    main = do
        currentURI <- getCurrentURI
        miso App
            { model = runRoute (Proxy @Routes) handler currentURI
            , view = mainView
            , ...
            }
```

Alternatively I am very much open to any suggestions on how else to avoid this tedious and error prone duplication. Feedback and suggestions welcome.

**Comment by dmjio** [comment]
@tysonzero Hello! Will try to answer as best I can.

> and one issue I am currently running into is that I need both the client and the server to be able to handle the same set of routes.

There's a few reasons for this, the largest one being that anything but a `Get` request doesn't really make sense on the server when implementing routing w/ isomorphic js. Miso has a closed type family to convert a client side type of `View action` into a server side view of `Get '[Html] (Wrapper (View a))`. (`View a` also has a `ToHtml` instance). The source of https://haskell-miso.org illustrates this:

https://github.com/dmjio/miso/blob/master/examples/haskell-miso.org/server/Main.hs#L46

> Currently this requires doing the routing twice, once in a way that Servant can handle, and once in a way that Miso can handle.

Even if we were to share the exact same router type on client and server, you'd still perform routing twice. This is because in an isomorphic context, the server receives the request, routes it to the correct servant handler (1), warp sends the bytes to the browser, the browser receives the html, parses into the DOM, the js bootstraps, detects the current URI, constructs a model for it (if necessary), generates a view that is isomorphic to the DOM from the model, copies the pointers into the virtual from the real DOM, then routes locally to the correct place using the `pushState` API (2), and lastly sets up event delegation and the app becomes interactive.

In regards to sharing across client / server, handlers for the client should be shared with the server (which are just `model -> View  a`, but not the other way around. This is because `IO` that is performed inside a server handler isn't appropriate for the client. 

> It would thus be ideal if there was a mapping function that applied a -> b to the leaves of all homogenous handlers. Just like what can currently be done with hoistServer, except operating on the entire leaves (both the monad and the type contained within the monad) instead of just the monad.

I see no reason why a custom monad stack (where you use `hoistServer`) would be incompatible w/ `ToServerRoutes`.

Care to join the slack? https://haskell-miso-slack.herokuapp.com/ wouldn't mind talking more about it.

**Comment by tysonzero** [comment]
This can be handled generatively by applying the function as you create the routes, without needing any mapping after the fact. Closing.
