### ISSUE TITLE
Add servant-client-ghcjs to hackage and stackage

### ISSUE THREAD

**Issue by tysonzero** [haskell-servant/servant#939]
Title, it would be convenient to be able to install it from Hackage/Stackage. I'm assuming the current recommended way to install it is via Github?

**Comment by phadej** [comment]
Yes, currently from *GitHub*

**Comment by tysonzero** [comment]
Alright will do, any ETA on when it will be on hackage / stackage etc.?

**Comment by alpmestan** [comment]
Were we not stuck on CI for servant-client-ghcjs?

**Comment by phadej** [comment]
Hmm, shouldn't -ghcjs package be buildable with normal GHC too (at least with small amount of CPP?) That would be good start

**Comment by ElvishJerricco** [comment]
If you're using the `ghcjs-dom` for all browser calls and not the JS FFI, you don't need to do anything to build with GHC. It will automatically fallback to the jsaddle backend.

**Comment by arianvp** [comment]
Oh that would be interesting.  @FPtje do you know about the `ghcjs-dom` package? 
We could at least use it to make `servant-client-ghcjs` run on   GHC and run the unit tests.   A more noble goal would be to merge `servant-client` and `servant-client-ghcjs` but that would be a next step.

**Comment by FPtje** [comment]
I do, yeah. I've refrained from using it because its jsaddle dependency is a rather bulky one. 

By the way, I'm sure we can make `servant-client-ghcjs` build with ghc, but that might give the false impression that it also actually *works* with ghc. That might be technically possible with jsaddle, but I reckon it still wouldn't be desirable because `servant-client` would be the right choice anyway. To get it to work on CI I'd recommend trying to get the ghcjs compiler to work.

**Comment by ElvishJerricco** [comment]
I would recommend getting this to work via jsaddle. The ability to run reflex-dom apps via GHC+jsaddle is critical to my productivity with it. Dev cycles are literally an order of magnitude faster when you can `:r` in GHCi instead of waiting on GHCJS's slow compile times. When building frontends with GHC+jsaddle, it would be far more desirable to be able to use the same client library, knowing that it's using the same browser API that the GHCJS app will be using.

**Comment by alpmestan** [comment]
Sorry, I somehow missed this. Yes we could certainly move it under haskell-servant.

**Comment by roberth** [comment]
@alpmestan See #1018

**Comment by phadej** [comment]
I migrated servant-jsaddle to own repository, I consider the two remaining issues https://github.com/haskell-servant/servant-jsaddle/issues/2 and https://github.com/haskell-servant/servant-jsaddle/issues/1 blocking the release.

Closing this issue in favour of the other two.

**Comment by tysonzero** [comment]
I don't see how those issues address `servant-client-ghcjs` being on hackage/stackage.
